### ISSUE TITLE
List installed Packages (and create new Package)

### ISSUE THREAD

**Issue by deanrad** [MeteorToys/allthings#1]
Hi Max,
  I've built a tool that lets you start a new package while developing your app. I'm curious if you'd be interested in integrating this with Mongol ? 

https://github.com/chicagogrooves/meteor-package-kitchen

**Comment by msavin** [comment]
Hey man, I think its a great package. It's nice how it installs the packages into your app. However, I do not think it fits into Meteor Toys debugging goals.
