### ISSUE TITLE
Location in collection not resetting on user switch.

### ISSUE THREAD

**Issue by joerodrig** [MeteorToys/allthings#10]
When switching between users that have varying read privileges for a collection, the location your at in that collection doesn't reset.

ie. 
(i) You're an admin and have a "user" collection with 10 people (at location 1/10 in user collection)
(ii) You iterate the collection to the second person (2/10 in the user collection)
(iii)You impersonate a normal user who can only see themself in the user collection 

At the final step, you should see 1/1 in the user collection but instead appears as 2/1 without the ability to increment/decrement in the collection. My current work around is to switch back to the previous user and decrement the collection until it's back to 1

**Comment by msavin** [comment]
Thanks for reporting this issue. This is in some ways an accounted for limitation in Mongol; when you try to move between those documents, it will take you to the closest one if the one before/after is not available.

To adjust the document position in Mongol as the number of documents change, I would have to spin up Tracker for each collection. I am not sure if this is something people would want, but I'd love to hear other opinions.

**Comment by joerodrig** [comment]
Since Mongol seems to already track the length of a collection, would it be simpler to potentially have the increment button in Mongol bring you back to the first document in the collection if you click it while your at or above the last document in that collection?
 It wouldn't resolve the whole issue, but it'd allow a user to manually fix the problem in one click(ie. clicking increment at 5/1 to reset the collection back down to 1/1) without adding much overhead.

**Comment by msavin** [comment]
It does that automatically, but you spotted a bug when there is only one document in the collection, which has now been fixed :)
