### ISSUE TITLE
 Constraint meteortoys:toggle@4.0.0 is not satisfied by meteortoys:toggle 3.0.0.

### ISSUE THREAD

**Issue by Jogibaer1963** [MeteorToys/allthings#102]
When updating from version 3.0 to 4.0 I get the error message 
error: Conflict: Constraint meteortoys:toggle@4.0.0 is not satisfied by meteortoys:toggle 3.0.0.

first step was removing 3.0.0
then 
meteor add meteortoys:allthing@4.0.0 
(meteor add  without Version 4.0.0 installs 3.0.0)

**Comment by msavin** [comment]
Ouch! Updated the toggle package.. not sure how that was missed. Should be working now.
