### ISSUE TITLE
cannot get shell to work at all

### ISSUE THREAD

**Issue by 1jerry** [MeteorToys/allthings#103]
> To enable Shell,  you must set METEORTOYSSHELLENABLED as a `true` global variable on the server.

...is what is says in v4.  Previously it said METEORTOYSSHELL=true on the server.
I have tried both, using both "true" and "1", setting user AND system environment variables, closing and re-opening both the cmd.exe window AND the browser.  **I cannot get it to work,** and have not been able to for almost two years now.  What's the secret?  What _exactly_ do I need to do to get this to work?

I don't know what is meant by "global variable on the server".  I interpert that to mean a system environment variable named METEORTOYSSHELLENABLED or METEORTOYSSHELL (not being sure if this is a _change_ or a _typo_, since I cannot find a changelog).
I am not a "server".  I am using a [Windows 10] PC for development and am running "meteor" from the command prompt.

**Comment by msavin** [comment]
@1jerry sorry for the late response here.. not sure if this was fixed or not. I just tested locally and it worked.

Can you run meteor shell and ensure that `METEORTOYSSHELLENABLED` is `true`?

The check is literally this:

```javascript
if (typeof METEORTOYSSHELLENABLED === "boolean") {
			if (METEORTOYSSHELLENABLED === true) {
```

I made it two if statements just out of (warrantless) caution

**Comment by msavin** [comment]
maybe you are declaring this variable inside of a file that uses modules? I believe Meteor does a bit of magic there

**Comment by msavin** [comment]
Closing this out due to age. Please try the new version and these tips. If the issue persists, please let me know.
