### ISSUE TITLE
Monitor traffic on another DDP connect channel?

### ISSUE THREAD

**Issue by brucejo75** [MeteorToys/allthings#104]
Hi, I am loving MeteorToys.

But for my main project I want/need to monitor communications on a different channel other than the main one that Meteor opens up.

My app maintains the main connection to a server which serves up the accounts information.  It also opens a 2nd connection to my main server for publish / subscribe and method operations.

Is there a way to point MeteorToys at this 2nd channel?

Thanks!

**Comment by msavin** [comment]
Unfortunately, this is not something that I could support in Meteor Toys right now. There should be some open source DDP monitoring libraries that you could repurpose for this need.
