### ISSUE TITLE
Meteor UP shows Meteor Toys / Mongol in Production

### ISSUE THREAD

**Issue by kenshinman** [MeteorToys/allthings#106]
Hi, I just confirmed that this package is display on Production mode. How can I disable this on production.

I'm sure my deployed app is in Production by running `Meteor.isProduction` in the console and it's true. 

Uninstalling it for now till this is solved

Thanks

**Comment by msavin** [comment]
Hmm - can you tell me more about your setup? I just did a test and it
worked as it should.

 [image: Inline image 1]

**Comment by NathanJeanDevs** [comment]
I'm also seeing meteortoys:allthings after deploying with [mup](https://github.com/zodern/meteor-up)

In the past it would ignore this package when bundling, but now it is included in the bundle and then deployed. 

Here are my packages
```
meteor-base@1.1.0             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.2.0                   # The database Meteor supports right now
blaze-html-templates@1.0.4 # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.4   # CSS minifier run for production mode
standard-minifier-js@2.1.1    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers
ecmascript@0.8.2              # Enable ECMAScript2015+ syntax in app code
shell-server@0.2.4            # Server-side component of the `meteor shell` command

fourseven:scss
meteortoys:allthings
react-meteor-data
themeteorchef:bert
email@1.2.3
alanning:roles
accounts-password@1.4.0
accounts-base@1.3.2
edgee:slingshot
http
audit-argument-checks
```

**Comment by NathanJeanDevs** [comment]
I also uninstalled before deploying to remove it from my deployment and server. That is why meteor toys in not included in the list above. 

This has happened to me twice, happy to help diagnose what is causing this. Its a great package. But I also can't risk accidentally deploying this if it gets bundled. 

Thanks!

**Comment by NathanJeanDevs** [comment]
My guess is that Meteor's build process is not recognizing the package as `debugOnly`. 
I'm not really sure how to diagnose that

**Comment by ghost** [comment]
Is there a solution for this yet? I'm having the same problem when using MUP.

**Comment by msavin** [comment]
It sounds like this is an issue with MUP? For some reason, its ignoring the debugOnly flag. Can you try to your app with `meteor --production` and confirm>?

You might want to open a ticket for MUP as well.

**Comment by ghost** [comment]
I just checked it using `meteor --production` it loads as expected, MeteorToys doesn't load which is good. I've posted a question to Meteor-up. Hopefully, someone can confirm and provide guidance. 
If you have some time and don't mind having a look at the docs `http://meteor-up.com/docs.html` to see if there is something that we're all missing, I'm sure everyone would really appreciate it. I'm a noob so it might be very obvious to you. Thanks for your quick response.

**Comment by msavin** [comment]
In their code samples, they show using debugMode. I'm guessing people are
just copy and pasting that, and that's why the issue is happening:

```
meteor: {
  buildOptions: {
    // build with the debug mode on
    debug: true,
    // mobile setting for cordova apps
    mobileSettings: {
      public: {
        'meteor-up': 'rocks',
      }
    },
    // executable used to build the meteor project
    // you can set a local repo path if needed
    executable: 'meteor',
  }}
```

**Comment by ghost** [comment]
Ok, great. I'm not sure what it does overall, however, if you change `debug: false` it builds the production version correctly. Thanks for that @msavin I wouldn't have picked up on that.

**Comment by zodern** [comment]
I updated the docs for the next version to better explain the `debug` option. Also, I set it to `false` in all of the example configs.

**Comment by msavin** [comment]
@zodern was planning to notify you - glad you got to it 👍
