### ISSUE TITLE
Cannot toggle autopublish button

### ISSUE THREAD

**Issue by rolljee** [MeteorToys/allthings#109]
Hello, i ran into a strange problem recently : 

![screen shot 2018-03-23 at 14 40 54](https://user-images.githubusercontent.com/10114634/37832219-503e63ca-2ea8-11e8-8d93-857002ba37a3.png)

I cannot toggle the autopublish button anymore

Any browser are blocked

- safari
- chrome
- firefox

**Comment by msavin** [comment]
Can you try with Meteor Toys 7.0 and see if it persists?

**Comment by rolljee** [comment]
Hello, It's been a long time since I managed to make it work again.
Didn't has the same problem ever again.

For the record,

1. I've deleted all cached package inside my .meteor (~/home/user/.meteor ) install
1. Uninstalled all package inside my app, 
1. Ran `meteor reset`
1. Re-installed all packages

Then it worked again 👍

**Comment by landland** [comment]
Same issue for me. I haven't been able to resolve it. It would just crush my Macbook Pro and there was no way to turn it off, so I had to uninstall the package, unfortunately. Uninstalling/reinstalling didn't turn off autopublish, so right now I've had to remove the package completely. @msavin any ideas on how to turn off autopublish when I reinstall the package?

**Comment by rolljee** [comment]
Have you try uninstall-reinstall meteor itself ?

Normally erase cached package data inside your meteor install and your app should resolve this issue

**Comment by msavin** [comment]
`Package["meteortoys:autopub"].disable()` will disable the package in case
there is too much data being published and the client goes crazy
