### ISSUE TITLE
what is the default port that meteortoys listen

### ISSUE THREAD

**Issue by balasivagnanam** [MeteorToys/allthings#11]
Ctrl + M doesn't work in my case(is it because of windows?) and if I try to load the port 4000, there is nothing there, my app is listening to 3000 and 3000 admin is occupied by houston:admin for me. 
Later I removed houston admin and still I couldn't get it work.
Later I removed meteortoys and reinstalled it and still I couldn't get it work.

**Comment by msavin** [comment]
I don't think that's the issue. Can you try running Session.set("MeteorToys_display", true) in the console to see if that activates them? If not, please send me more details about your config and package list.

**Comment by balasivagnanam** [comment]
these are the things happened:
![image](https://cloud.githubusercontent.com/assets/4233785/8075071/0758f08c-0f6e-11e5-8fb2-bd4829fa206e.png)
and this is my package list
![image](https://cloud.githubusercontent.com/assets/4233785/8075073/145903f8-0f6e-11e5-9d8c-3ccad5882339.png)

**Comment by msavin** [comment]
This may have been fixed - can you please update to Mongol 1.0.100 and see if the issue has went away?

**Comment by msavin** [comment]
Assuming it worked, if not please let me know

**Comment by balasivagnanam** [comment]
yes yes, it worked.. sorry I forgot to update..
