### ISSUE TITLE
add check to methods to pass validation with audit-argument-checks

### ISSUE THREAD

**Issue by aaronjudd** [MeteorToys/allthings#12]
`audit-argument-checks` being a commonly required package for validating method arguments.

Causes validation errors to occur:

```
Exception from sub MeteorToys id wmSW9p5Yj6tFz77LP Error: Did not check() all arguments during publisher 'MeteorToys'
Exception while invoking method 'Mongol_verifyDoc' Error: Did not check() all arguments during call to ‘Mongol_verifyDoc'
```

**Comment by flt123** [comment]
Were you able to resolve this issue? I'm having same issue

**Comment by aaronjudd** [comment]
@fit213 `meteortoys:allthings@1.2.0` seems to work for me.

**Comment by flt123** [comment]
ok, thks

**Comment by nilsi** [comment]
Im still getting this after installing by "meteor add msavin:mongol".

Edit: Solved by `meteor remove matteodem:easy-security;`
