### ISSUE TITLE
Filter out the noise

### ISSUE THREAD

**Issue by derekclair** [MeteorToys/allthings#13]
I think it would be just swell if I could enable a filter to get rid of all the noise made by other monitoring/debugging packages. For example, the new Kadira Debugging, or Velocity tests. It may be amateurish for me to want them excluded (and rightfully so, I am one), but I believe it to be core to the MeteorToys use-case, that the tool focus on my code and not the methods, pubs, subs, and variables those other tools depend on. Just my thoughts, and thanks for the great tool!

**Comment by alesch** [comment]
@derekclair see #5.

**Comment by msavin** [comment]
Since Velocity is now part of core, it seems reasonable to add a shortcut for it. Please review the updated README for more details: https://github.com/msavin/Mongol
