### ISSUE TITLE
Reactive-Dict Support?

### ISSUE THREAD

**Issue by praneybehl** [MeteorToys/allthings#18]
Hi mate,

Its seems I am missing something, as it says on http://meteor.toys that there is support for Reactive-Var and Reactive-Dict, but I can't seem to find how to track them. I have 1 Reactive-Dict on the global scope and some at template level.

A little help will be appreciated.
Thanks

**Comment by praneybehl** [comment]
I am sorry mate but almost a week and no reply. I feel bad for paying for such a tool with no support.

**Comment by praneybehl** [comment]
It doesn't seem like there will be any support for this paid package. Please cancel my license and refund.

**Comment by msavin** [comment]
Refunded. Support for RD coming soon - there was a bit of a challenge with it.
