### ISSUE TITLE
Listening to DDP and toggling toys cause chrome console to be flooded

### ISSUE THREAD

**Issue by mordrax** [MeteorToys/allthings#19]
I've been having this issue since version 1, if you start the ddp listener then Ctrl+M twice to hide and reshow toys, chrome floods with these messges:

IN   Object {msg: "updated", methods: Array[1]} main.js:61 
IN   Object {msg: "result", id: "1003", result: Array[31]} main.js:61 

In 1.1.4 I had to kill chrome fast before it locked up the PC, now it stops when I hide toys, however ddp listening is still unusable.

**Comment by msavin** [comment]
Thanks for the tip - looking into it

**Comment by msavin** [comment]
This issue is resolved the new 2.2.0 release. To update, remove your Meteor Toys package and run `meteor add meteortoys:allthings@2.2.0`. If this issue repeats, or you have other issues, please let me know. :)
