### ISSUE TITLE
Server console flooded with logs

### ISSUE THREAD

**Issue by mordrax** [MeteorToys/allthings#21]
I'm getting this in my webstorm console when running with toys. Is there something I can do to silence it?

I20150730-13:32:17.085(10)? [ { name: 'users',
I20150730-13:32:17.085(10)?     instance: 
I20150730-13:32:17.086(10)?      { _makeNewID: [Function],
I20150730-13:32:17.086(10)?        _transform: [Function],
I20150730-13:32:17.086(10)?        _connection: [Object],
I20150730-13:32:17.086(10)?        _collection: [Object],
I20150730-13:32:17.086(10)?        _name: 'users',
I20150730-13:32:17.086(10)?        _driver: [Object],
I20150730-13:32:17.086(10)?        _restricted: true,
I20150730-13:32:17.086(10)?        _insecure: undefined,
I20150730-13:32:17.087(10)?        _validators: [Object],
I20150730-13:32:17.087(10)?        _prefix: '/users/',
I20150730-13:32:17.087(10)?        before: [Object],
I20150730-13:32:17.087(10)?        _hookAspects: [Object],
I20150730-13:32:17.087(10)?        after: [Object],
I20150730-13:32:17.087(10)?        hookOptions: [Object],
I20150730-13:32:17.087(10)?        direct: [Object],
I20150730-13:32:17.087(10)?        _c2: [Object],
I20150730-13:32:17.087(10)?        _helpers: [Function: Document],
I20150730-13:32:17.087(10)?        _denormalize: [Object] },
I20150730-13:32:17.088(10)?     options: undefined },
I20150730-13:32:17.088(10)?   { name: 'MeteorToys_Impersonate',
I20150730-13:32:17.088(10)?     instance: 
I20150730-13:32:17.088(10)?      { _makeNewID: [Function],
I20150730-13:32:17.088(10)?        _transform: null,
I20150730-13:32:17.088(10)?        _connection: [Object],
I20150730-13:32:17.088(10)?        _collection: [Object],
I20150730-13:32:17.088(10)?        _name: 'MeteorToys_Impersonate',
I20150730-13:32:17.088(10)?        _driver: [Object],
I20150730-13:32:17.088(10)?        _restricted: true,
I20150730-13:32:17.089(10)?        _insecure: undefined,
I20150730-13:32:17.089(10)?        _validators: [Object],
I20150730-13:32:17.089(10)?        _prefix: '/MeteorToys_Impersonate/',
I20150730-13:32:17.089(10)?        before: [Object],
I20150730-13:32:17.089(10)?        _hookAspects: [Object],
I20150730-13:32:17.089(10)?        after: [Object],
I20150730-13:32:17.089(10)?        hookOptions: [Object],
I20150730-13:32:17.089(10)?        direct: [Object] },
I20150730-13:32:17.089(10)?     options: undefined },
I20150730-13:32:17.089(10)?   { name: 'MeteorToys_JetSetter',
I20150730-13:32:17.089(10)?     instance: 
I20150730-13:32:17.090(10)?      { _makeNewID: [Function],
I20150730-13:32:17.090(10)?        _transform: null,
I20150730-13:32:17.090(10)?        _connection: [Object],
I20150730-13:32:17.090(10)?        _collection: [Object],
I20150730-13:32:17.090(10)?        _name: 'MeteorToys_JetSetter',
I20150730-13:32:17.090(10)?        _driver: [Object],
I20150730-13:32:17.090(10)?        _restricted: true,
I20150730-13:32:17.090(10)?        _insecure: undefined,
I20150730-13:32:17.090(10)?        _validators: [Object],
I20150730-13:32:17.090(10)?        _prefix: '/MeteorToys_JetSetter/',
I20150730-13:32:17.090(10)?        before: [Object],
I20150730-13:32:17.091(10)?        _hookAspects: [Object],
I20150730-13:32:17.091(10)?        after: [Object],
I20150730-13:32:17.091(10)?        hookOptions: [Object],
I20150730-13:32:17.091(10)?        direct: [Object] },
I20150730-13:32:17.091(10)?     options: undefined },
I20150730-13:32:17.091(10)?   { name: 'MeteorToys_Mongol',
I20150730-13:32:17.091(10)?     instance: 
I20150730-13:32:17.091(10)?      { _makeNewID: [Function],
I20150730-13:32:17.092(10)?        _transform: null,
I20150730-13:32:17.092(10)?        _connection: [Object],
I20150730-13:32:17.092(10)?        _collection: [Object],
I20150730-13:32:17.092(10)?        _name: 'MeteorToys_Mongol',
I20150730-13:32:17.092(10)?        _driver: [Object],
I20150730-13:32:17.092(10)?        _restricted: true,
I20150730-13:32:17.092(10)?        _insecure: undefined,
I20150730-13:32:17.092(10)?        _validators: [Object],
I20150730-13:32:17.092(10)?        _prefix: '/MeteorToys_Mongol/',
I20150730-13:32:17.092(10)?        before: [Object],
I20150730-13:32:17.093(10)?        _hookAspects: [Object],
I20150730-13:32:17.093(10)?        after: [Object],
I20150730-13:32:17.093(10)?        hookOptions: [Object],
I20150730-13:32:17.093(10)?        direct: [Object] },
I20150730-13:32:17.093(10)?     options: undefined },
I20150730-13:32:17.093(10)?   { name: 'MeteorToys_AutoPub',
I20150730-13:32:17.093(10)?     instance: 
I20150730-13:32:17.093(10)?      { _makeNewID: [Function],
I20150730-13:32:17.093(10)?        _transform: null,
I20150730-13:32:17.093(10)?        _connection: [Object],
I20150730-13:32:17.093(10)?        _collection: [Object],
I20150730-13:32:17.094(10)?        _name: 'MeteorToys_AutoPub',
I20150730-13:32:17.094(10)?        _driver: [Object],
I20150730-13:32:17.094(10)?        _restricted: true,
I20150730-13:32:17.094(10)?        _insecure: undefined,
I20150730-13:32:17.094(10)?        _validators: [Object],
I20150730-13:32:17.094(10)?        _prefix: '/MeteorToys_AutoPub/',
I20150730-13:32:17.094(10)?        before: [Object],
I20150730-13:32:17.094(10)?        _hookAspects: [Object],
I20150730-13:32:17.094(10)?        after: [Object],
I20150730-13:32:17.094(10)?        hookOptions: [Object],
I20150730-13:32:17.094(10)?        direct: [Object] },
I20150730-13:32:17.095(10)?     options: undefined },
I20150730-13:32:17.095(10)?   { name: 'MeteorToysCredentials',
I20150730-13:32:17.095(10)?     instance: 
I20150730-13:32:17.095(10)?      { _makeNewID: [Function],
I20150730-13:32:17.095(10)?        _transform: null,
I20150730-13:32:17.095(10)?        _connection: [Object],
I20150730-13:32:17.095(10)?        _collection: [Object],
I20150730-13:32:17.095(10)?        _name: 'MeteorToysCredentials',
I20150730-13:32:17.096(10)?        _driver: [Object],
I20150730-13:32:17.096(10)?        _restricted: false,
I20150730-13:32:17.096(10)?        _insecure: undefined,
I20150730-13:32:17.096(10)?        _validators: [Object],
I20150730-13:32:17.096(10)?        _prefix: '/MeteorToysCredentials/',
I20150730-13:32:17.096(10)?        before: [Object],
I20150730-13:32:17.096(10)?        _hookAspects: [Object],
I20150730-13:32:17.096(10)?        after: [Object],
I20150730-13:32:17.096(10)?        hookOptions: [Object],
I20150730-13:32:17.097(10)?        direct: [Object] },
I20150730-13:32:17.097(10)?     options: undefined },
I20150730-13:32:17.097(10)?   { name: 'esCounts',
I20150730-13:32:17.097(10)?     instance: 
I20150730-13:32:17.097(10)?      { _makeNewID: [Function],
I20150730-13:32:17.097(10)?        _transform: null,
I20150730-13:32:17.097(10)?        _connection: [Object],
I20150730-13:32:17.097(10)?        _collection: [Object],
I20150730-13:32:17.097(10)?        _name: 'esCounts',
I20150730-13:32:17.098(10)?        _driver: [Object],
I20150730-13:32:17.098(10)?        _restricted: false,
I20150730-13:32:17.098(10)?        _insecure: undefined,
I20150730-13:32:17.098(10)?        _validators: [Object],
I20150730-13:32:17.098(10)?        _prefix: '/esCounts/',
I20150730-13:32:17.099(10)?        before: [Object],
I20150730-13:32:17.099(10)?        _hookAspects: [Object],
I20150730-13:32:17.099(10)?        after: [Object],
I20150730-13:32:17.100(10)?        hookOptions: [Object],
I20150730-13:32:17.100(10)?        direct: [Object] },
I20150730-13:32:17.100(10)?     options: undefined },
I20150730-13:32:17.100(10)?   { name: 'members',
I20150730-13:32:17.100(10)?     instance: 
I20150730-13:32:17.100(10)?      { _makeNewID: [Function],
I20150730-13:32:17.100(10)?        _transform: [Function],
I20150730-13:32:17.100(10)?        _connection: [Object],
I20150730-13:32:17.100(10)?        _collection: [Object],
I20150730-13:32:17.101(10)?        _name: 'members',
I20150730-13:32:17.101(10)?        _driver: [Object],
I20150730-13:32:17.101(10)?        _restricted: true,
I20150730-13:32:17.101(10)?        _insecure: undefined,
I20150730-13:32:17.101(10)?        _validators: [Object],
I20150730-13:32:17.101(10)?        _prefix: '/members/',
I20150730-13:32:17.101(10)?        before: [Object],
I20150730-13:32:17.101(10)?        _hookAspects: [Object],
I20150730-13:32:17.102(10)?        after: [Object],
I20150730-13:32:17.102(10)?        hookOptions: [Object],
I20150730-13:32:17.102(10)?        direct: [Object],
I20150730-13:32:17.102(10)?        _c2: [Object],
I20150730-13:32:17.102(10)?        _helpers: [Function: Document],
I20150730-13:32:17.102(10)?        _denormalize: [Object] },
I20150730-13:32:17.102(10)?     options: undefined },
I20150730-13:32:17.102(10)?   { name: 'messageData',
I20150730-13:32:17.102(10)?     instance: 
I20150730-13:32:17.103(10)?      { _makeNewID: [Function],
I20150730-13:32:17.103(10)?        _transform: [Function],
I20150730-13:32:17.103(10)?        _connection: [Object],
I20150730-13:32:17.103(10)?        _collection: [Object],
I20150730-13:32:17.103(10)?        _name: 'messageData',
I20150730-13:32:17.103(10)?        _driver: [Object],
I20150730-13:32:17.103(10)?        _restricted: true,
I20150730-13:32:17.103(10)?        _insecure: undefined,
I20150730-13:32:17.103(10)?        _validators: [Object],
I20150730-13:32:17.103(10)?        _prefix: '/messageData/',
I20150730-13:32:17.104(10)?        before: [Object],
I20150730-13:32:17.104(10)?        _hookAspects: [Object],
I20150730-13:32:17.104(10)?        after: [Object],
I20150730-13:32:17.227(10)?        hookOptions: [Object],
I20150730-13:32:17.227(10)?        direct: [Object],
I20150730-13:32:17.228(10)?        _c2: [Object],
I20150730-13:32:17.228(10)?        _helpers: [Function: Document] },
I20150730-13:32:17.228(10)?     options: undefined },
I20150730-13:32:17.228(10)?   { name: 'messages',
I20150730-13:32:17.228(10)?     instance: 
I20150730-13:32:17.228(10)?      { _makeNewID: [Function],
I20150730-13:32:17.228(10)?        _transform: [Function],
I20150730-13:32:17.229(10)?        _connection: [Object],
I20150730-13:32:17.229(10)?        _collection: [Object],
I20150730-13:32:17.229(10)?        _name: 'messages',
I20150730-13:32:17.229(10)?        _driver: [Object],
I20150730-13:32:17.229(10)?        _restricted: true,
I20150730-13:32:17.229(10)?        _insecure: undefined,
I20150730-13:32:17.229(10)?        _validators: [Object],
I20150730-13:32:17.229(10)?        _prefix: '/messages/',
I20150730-13:32:17.229(10)?        before: [Object],
I20150730-13:32:17.230(10)?        _hookAspects: [Object],
I20150730-13:32:17.230(10)?        after: [Object],
I20150730-13:32:17.230(10)?        hookOptions: [Object],
I20150730-13:32:17.230(10)?        direct: [Object],
I20150730-13:32:17.230(10)?        _c2: [Object],
I20150730-13:32:17.230(10)?        _helpers: [Function: Document] },
I20150730-13:32:17.230(10)?     options: undefined },
I20150730-13:32:17.230(10)?   { name: 'organisations',
I20150730-13:32:17.231(10)?     instance: 
I20150730-13:32:17.231(10)?      { _makeNewID: [Function],
I20150730-13:32:17.231(10)?        _transform: [Function],
I20150730-13:32:17.231(10)?        _connection: [Object],
I20150730-13:32:17.231(10)?        _collection: [Object],
I20150730-13:32:17.231(10)?        _name: 'organisations',
I20150730-13:32:17.232(10)?        _driver: [Object],
I20150730-13:32:17.232(10)?        _restricted: true,
I20150730-13:32:17.232(10)?        _insecure: undefined,
I20150730-13:32:17.232(10)?        _validators: [Object],
I20150730-13:32:17.232(10)?        _prefix: '/organisations/',
I20150730-13:32:17.233(10)?        before: [Object],
I20150730-13:32:17.233(10)?        _hookAspects: [Object],
I20150730-13:32:17.233(10)?        after: [Object],
I20150730-13:32:17.233(10)?        hookOptions: [Object],
I20150730-13:32:17.233(10)?        direct: [Object],
I20150730-13:32:17.233(10)?        _c2: [Object],
I20150730-13:32:17.233(10)?        _helpers: [Function: Document],
I20150730-13:32:17.233(10)?        _denormalize: [Object] },
I20150730-13:32:17.233(10)?     options: undefined },
I20150730-13:32:17.233(10)?   { name: 'providers',
I20150730-13:32:17.234(10)?     instance: 
I20150730-13:32:17.234(10)?      { _makeNewID: [Function],
I20150730-13:32:17.234(10)?        _transform: null,
I20150730-13:32:17.234(10)?        _connection: [Object],
I20150730-13:32:17.234(10)?        _collection: [Object],
I20150730-13:32:17.234(10)?        _name: 'providers',
I20150730-13:32:17.234(10)?        _driver: [Object],
I20150730-13:32:17.234(10)?        _restricted: true,
I20150730-13:32:17.234(10)?        _insecure: undefined,
I20150730-13:32:17.234(10)?        _validators: [Object],
I20150730-13:32:17.234(10)?        _prefix: '/providers/',
I20150730-13:32:17.235(10)?        before: [Object],
I20150730-13:32:17.235(10)?        _hookAspects: [Object],
I20150730-13:32:17.235(10)?        after: [Object],
I20150730-13:32:17.235(10)?        hookOptions: [Object],
I20150730-13:32:17.235(10)?        direct: [Object],
I20150730-13:32:17.235(10)?        _c2: [Object] },
I20150730-13:32:17.235(10)?     options: undefined } ]

**Comment by msavin** [comment]
Ah strange - going to look into it soon. Any tips for replicating?

**Comment by msavin** [comment]
Fixed in 1.2.3, please update and enjoy :smile:
