### ISSUE TITLE
Error while add the package

### ISSUE THREAD

**Issue by eldadts** [MeteorToys/allthings#25]
Developer$ meteor add meteortoys:allthings

/Users/Developer/.meteor/packages/meteor-tool/.1.1.4.ehup04++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: Must throw non-empty error
    at Object.Future.throw (/Users/Developer/.meteor/packages/meteor-tool/.1.1.4.ehup04++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:259:10)
    at /Users/Developer/.meteor/packages/meteor-tool/.1.1.4.ehup04++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:541:23
    at runWithEnvironment (/Users/Developer/.meteor/packages/meteor-tool/.1.1.4.ehup04++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:139:21)
    at /Users/Developer/.meteor/packages/meteor-tool/.1.1.4.ehup04++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:146:14
    at /Users/Developer/.meteor/packages/meteor-tool/.1.1.4.ehup04++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:549:11

**Comment by mordrax** [comment]
Apparently this is happening for alot of devs across the globe:
https://forums.meteor.com/t/meteor-add-has-broken-this-morning/8181
for all packages, not just toys

**Comment by msavin** [comment]
Indeed - sorry you are having the issue. May be a good idea to post an issue to the official repo: 

https://github.com/meteor/meteor

**Comment by carlosacp** [comment]
I had the same error. It appears to be an issue with meteortoys:toykit@1.0.0

I downgrade meteortoys:allthings to 1.2.1, msavin:mongol to 1.1.0 and msavin:jetsetter to 1.0.19 and now I can use meteortoys:toykit@0.8.2 and the error just disappear.
