### ISSUE TITLE
Filter out MeteorToys communication

### ISSUE THREAD

**Issue by dandv** [MeteorToys/allthings#27]
When watching DDP messages, is there a way to filter out those that pertain to MeteorToys, which typically are only interesting when developing MeteorToys itself?

**Comment by msavin** [comment]
Coming in a new update

**Comment by msavin** [comment]
Hey Dan - between potential performance issues other reasons, I've decided this feature request may not make it to Meteor Toys. If anything changes, I'll let you know, and if there's anything else I can do to improve your Meteor Toys experience, please let me know.
