### ISSUE TITLE
Add Template toy

### ISSUE THREAD

**Issue by dandv** [MeteorToys/allthings#28]
I often want to evaluate template helpers.

See @prasadKodeInCloud's [meteor-client-debugger](https://github.com/prasadKodeInCloud/meteor-client-debugger).

**Comment by msavin** [comment]
Indeed - this is coming in Meteor Toys 2.0 :) looks like an interesting repo

**Comment by msavin** [comment]
Introducing Blueprint :) To upgrade, remove Meteor Toys then run `meteor add meteortoys:allthings@2.0.0`
