### ISSUE TITLE
See MongoDB statements when editing documents?

### ISSUE THREAD

**Issue by purplecones** [MeteorToys/allthings#29]
When making document changes via Mongol, is there a way to see the mongodb statement that is being executed by Mongol?

**Comment by msavin** [comment]
Not really. The changes happen through the server. You can study the files to see how it works. Can you please tell me what you are trying to do?

**Comment by purplecones** [comment]
Was building out a component that is doing some crud operations via methods. Since I am able to update documents via Mongol, thought I could take those update statements as a starting point for when I'm creating my methods. I guess it's more for convenience and transparency to see how Mongol is changing my data.

**Comment by msavin** [comment]
Hmmm, maybe you can record the original document before making changes, then diff the two.
