### ISSUE TITLE
License Key

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [MeteorToys/allthings#30]
Hi, I just bought the product and I don't know where to get my License Key... also tried to contact on the email and got no recipient...

**Comment by msavin** [comment]
Hey man - just sent it. Sorry for the delayed delivery.

**Comment by szmarci** [comment]
I bought it as well, but no license. I wrote an email about it, but it bounced back. Can you send it to me?

**Comment by msavin** [comment]
Sent yesterday - sorry for the delay!

**Comment by jonisapp** [comment]
Same here ...
