### ISSUE TITLE
Restore from Trash does not restore _id field

### ISSUE THREAD

**Issue by 0xpatrickdev** [MeteorToys/allthings#31]
I noticed that the restore on the trash assigns the document a new _id.  I have been using custom _id's on some collections, and when I restore documents from trash they are assigned a new objectId.

Not sure if you are assigning new _id's for a specific reason, but it could be helpful to restore the orginal _id as well!

Also is there any way to empty the trash? Does it ever reset? 

Thank you

**Comment by msavin** [comment]
Good point - I think I was being over-protective by removing and re-generating the ID. It's probably better that you can return it back to its original state. I'll work it on the next release.

**Comment by msavin** [comment]
This issue is resolved the new 2.2.0 release. To update, remove your Meteor Toys package and run `meteor add meteortoys:allthings@2.2.0`. If this issue repeats, or you have other issues, please let me know. :)
