### ISSUE TITLE
Disable feature in Meteor Toys

### ISSUE THREAD

**Issue by MomchilGorchev** [MeteorToys/allthings#33]
Hi, first thanks for the great tool!
My problem is that i have custom login form and custom functionality triggered after login, which includes external service call and database interactions in `Accounts.onLogin` block. I think the Authenticate feature of Meteor Toys takes control of the login/logout mechanism and my custom methods never gets called. 

So I'd like to ask is there a way to disable just the Authenticate feature from Meteor Toys and leave all the other tools switched on?

I tried `meteor remove meteortoys:authenticate` after installing meteortoys:allthings
but its saying `meteortoys:authenticate is not in this project`

Ideally I'd like to be able to configure it programatically with something like `{"authenticate": false}`
Please let me know if this is possible at all
Thanks in advance

**Comment by msavin** [comment]
Hi Momchil,

Thanks for the feedback. I'm working on a new release, and there should be a solution in that for it. I'll update you once its ready.

Best,
Max

**Comment by MomchilGorchev** [comment]
Hey Max,

Thanks for the reply, looking forward to that!

Best, 
MGorchev

**Comment by msavin** [comment]
Now there is a way :) 

https://github.com/MeteorToys/allthings/blob/master/CUSTOMIZE.md

**Comment by MomchilGorchev** [comment]
Hi Max,

thanks for the efforts, can you elaborate a bit more on this please. Following the instructions in the `CUSTOMISE.md` i should edit the `package.js` file from the repo and copy it to `my-project-folder/packages` ? Should that folder contains a `packages.json` file as well ?

Thank in advance
MGorchev

**Comment by msavin** [comment]
Momchil,

Yes - you need to copy that file into project/packages/meteortoys, comment out the toys you do not wish to use, and then run meteor add meteortoys:allthings :)

**Comment by MomchilGorchev** [comment]
Great job Max, everything is working!

Thanks again!
