### ISSUE TITLE
Ctrl+M just does not work anymore in chrome

### ISSUE THREAD

**Issue by came** [MeteorToys/allthings#35]
Hi,

just wanted to tell that for whatever reasons Ctrl+M does not work anymore on my mac. So far I haven't figured out where this come from. Safari is working fine. 
Is there any workaround - or a hint where I could look into?
Session.set("MeteorToys_display", true) doesn't work neither in chrome nor in safari.

BR, Carsten

**Comment by msavin** [comment]
Any chance you are running on Meteor 1.2? In that case, may be worth updating to Meteor Toys 2 to get over any compatibility issues.

**Comment by came** [comment]
I running meteortoys:allthings@2.0.0 on a fresh install of meteor --create todos.
Session.set("MeteorToys_display", true) isn't working neither in safari nor in chrome.
Ctrl-M is only working in safari. Is Session.set("MeteorToys_display", true) the correct session name? has anything changed?

BR, Carsten

**Comment by msavin** [comment]
In the new versions, I've been using Reactive-Dict to avoid polluting Session:
`Package["meteortoys:toykit"].MeteorToysDict.set("MeteorToys_display", true);`

It's odd that Chrome doesn't recognize Control + M - maybe there is some kind of extension blocking it?

**Comment by came** [comment]
ok ...Package["meteortoys:toykit"].MeteorToysDict.set("MeteorToys_display", true); enables meteor toys ...thanks a lot, this info was missing ;)

When I press Ctrl+M the cursor disappears and nothing is happening. It certainly has nothing todo with meteor toys. If I figure it out I will post it here.

**Comment by msavin** [comment]
Cool, thanks for letting me know. In the meanwhile, I'll close the issue :)

**Comment by abz121** [comment]
Still having this problem in Meteor Toys - Ctrl + M is NOT working!

I am using: Mac with latest version of Meteor & latest version of MeteorToys@3.x

Tried across all browsers - No luck (cursor just dissapears!)

Tried uninstalling/installing - everything!

(My Theory: The shortcut clashes with some of the browser shortcuts - e.g. in chrome pressing ctrl + M mutes the tab!)

Please help!

**Comment by msavin** [comment]
What os are you using? I can suggest adding meteortoys:toggle as an
alternative

**Comment by abz121** [comment]
Mac El Capitan 10.11.5

meteortoys:toggle added then ctrl + M - Still no luck!

**Comment by msavin** [comment]
that should display a toggle on the bottom left corner. If it's not then
it sounds like there's some kind of non MT bug. I can also suggest trying
to move the MT packages to the top of your package list

**Comment by abz121** [comment]
I have finally found a solution! I was using the Atom package 'meteor-helper' to launch my app and that was the problem. When using the system command line to launch meteor ITS NOW WORKING!!!!

Thank you to @msavin for your support. really appreciate it!

**Comment by Spartano** [comment]
sory for the dumb question, but does Meteor Toys  work on Windows?
