### ISSUE TITLE
Notification: Uncaught ReferenceError: Note is not defined

### ISSUE THREAD

**Issue by merlinstardust** [MeteorToys/allthings#37]
I would love to use Meteor Toys Notifications in my local development. However, I tried a simple `Note('test')` and received the error `Uncaught ReferenceError: Note is not defined`.

**Comment by msavin** [comment]
Ah.. I wrote that email late last night. To add notifications, you have to run:

`meteor add meteortoys:notifications`

I'll keep this open in the meanwhile in case people have the same question

**Comment by merlinstardust** [comment]
Thanks for the fast response. I just tried that and got `While adding package meteortoys:notifications:
error: no such package`

**Comment by msavin** [comment]
I forgot to publish the package - please try again

**Comment by merlinstardust** [comment]
Success! Thank you!
