### ISSUE TITLE
CTRL+M not opening Meteor Toys widgets

### ISSUE THREAD

**Issue by iamjaredwalters** [MeteorToys/allthings#40]
Using `meteortoys:allthings 2.0.0` and `Meteor 1.2` I'm unable to open up the Meteor Toys UI.  I've tested in Chrome, Safari, Firefox on OSX 10.10.5  and it doesnt seem to work in any of those browsers.  Meteor Toys is listed in `meteor  list` and I've uninstalled/reinstalled to no avail.

**Comment by Anima-t3d** [comment]
Same here, after I got corrupted previous version I updated to get my build running. Now I can build the app but the widgets are not showing up...

**Comment by peonmodel** [comment]
+1, same here, ctrl-m doesnt work.
Also, is there a way to call up the menu without Ctrl-M? like an option to open the widget at startup?

**Comment by praneybehl** [comment]
Yeah same problem here.

**Comment by sgoudie** [comment]
I'm getting the same issue and I wonder if it's something to do with browser policy? Since the last update I've got this message in the console:

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'
```

It points to line 531 of `meteortoys-toykit.js`

**Comment by arunoda** [comment]
I also can't get this working. But I don't get any error message in the console.

**Comment by skeltoras** [comment]
+1, same here and no error message in console.

**Comment by parhelium** [comment]
+1 cannot open as well

**Comment by matikucharski** [comment]
+1

**Comment by msavin** [comment]
Hey folks - apologies for the issue. It's very strange since everyone reported the previous patch things working. I re-published the package and it looks like its working now.

**Comment by skeltoras** [comment]
Seems to be working now. Thanks for the quick fix.

**Comment by iamjaredwalters** [comment]
Update works for me.  Much appreciated.  Closing the issue :)
