### ISSUE TITLE
What do I do with the license?

### ISSUE THREAD

**Issue by agad** [MeteorToys/allthings#42]
Bought a license and received it.  Now what do I do with it?  I have downloaded allthings and it works.  But I can't take advantage of the Pro versions since I don't know what to do with the license.  I've looked all over the site but can't figure it out.  So its probably very obvious and staring me in the face ;).  Any help appreciated.

**Comment by Anima-t3d** [comment]
Top left icon you could authenticate yourself with. Enter e-mail and pass.

**Comment by msavin** [comment]
Indeed - please let me know if you still have trouble

**Comment by agad** [comment]
Got it - the icons was totally obscured because it blended into the header of the site I am working on.  Thanks!
