### ISSUE TITLE
xxx.meteor.com 'MeteorToysDict' of undefined

### ISSUE THREAD

**Issue by merlinstardust** [MeteorToys/allthings#43]
I just attempted to deploy my app to a meteor.com sub domain. Unfortunately, I see an Iron Router splash page and when I open up the console, I see `Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined`. I thought that because Toys is `debugOnly`, it didn't get deployed. Is that incorrect?

I could just as easily remove it before I deploy but having to do that every time and then re add it would quickly become frustrating.

**Comment by msavin** [comment]
Hey man, thanks for letting me know. Any chance you have notifications package?

**Comment by merlinstardust** [comment]
Yes, I have the notifications package. Shall I remove it and see if that fixes it?

**Comment by merlinstardust** [comment]
I removed it and that worked so the issue definitely lies there.

**Comment by msavin** [comment]
The notifications 2.0 package should have that squared away - please let me know how it works.

**Comment by merlinstardust** [comment]
Unfortunately that did not fix it. Now I get the error `Uncaught TypeError: Cannot read property 'Note' of undefined` which points to

`!function(){var o=Package.meteor.Meteor,e;(function(){e=function(o,e){console.log(o),e&&console.log(e)},Package["meteortoys:toykit"].Note&&(e=Package["meteortoys:toykit"].Note)}).call(this),"undefined"==typeof Package&&(Package={}),Package["meteortoys:notifications"]={Note:e}}();`

**Comment by msavin** [comment]
This issue is resolved the new 2.2.0 release. To update, remove your Meteor Toys package and run `meteor add meteortoys:allthings@2.2.0`. If this issue repeats, or you have other issues, please let me know.

To get notifications working again, you would need to re-add the notifications package:
https://github.com/MeteorToys/notifications
