### ISSUE TITLE
Error when deleting User from Meteor.users

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [MeteorToys/allthings#44]
Exception while invoking method 'Mongol_remove' TypeError: Cannot set property 'Mongol_origin' of undefined
I20151005-01:53:10.644(-3)?     at [object Object].Meteor.methods.Mongol_remove (packages/msavin_mongol/packages/msavin_mongol.js:334:1)
I20151005-01:53:10.644(-3)?     at maybeAuditArgumentChecks (livedata_server.js:1692:12)
I20151005-01:53:10.644(-3)?     at livedata_server.js:708:19
I20151005-01:53:10.644(-3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151005-01:53:10.644(-3)?     at livedata_server.js:706:40
I20151005-01:53:10.644(-3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151005-01:53:10.645(-3)?     at livedata_server.js:704:46
I20151005-01:53:10.645(-3)?     at tryCallTwo (/home/rafa93br/.meteor/packages/promise/.0.5.0.1n467xz++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151005-01:53:10.645(-3)?     at doResolve (/home/rafa93br/.meteor/packages/promise/.0.5.0.1n467xz++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20151005-01:53:10.645(-3)?     at new Promise (/home/rafa93br/.meteor/packages/promise/.0.5.0.1n467xz++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)

**Comment by msavin** [comment]
This should be corrected - please let me know if the new version worked. To update, remove and re-add the packages.

**Comment by msavin** [comment]
Closing on the assumption that this is working now
