### ISSUE TITLE
Hotreload ReferenceError: Match is not defined

### ISSUE THREAD

**Issue by adambharris** [MeteorToys/allthings#47]
"Exception while invoking method 'MeteorToys_method_handlers' ReferenceError: Match is not defined"

It seems the "check" package should be listed as a dependency of your hotreload toy package. In the meantime, I'm able to fix the error by manually adding it as a top level dependency.

**Comment by msavin** [comment]
Good one, thanks for letting me know. I just pushed an update. Please let me know if it worked.

**Comment by msavin** [comment]
Closing on the assumption that this is working now
