### ISSUE TITLE
Hide collections that have no documents on clients yet?

### ISSUE THREAD

**Issue by jasonxeno** [MeteorToys/allthings#5]
Would it be possible to make a feature to hide collections that currently have 0 documents on the client?

**Comment by msavin** [comment]
You can write a Tracker script that does that, using: 
- Collection.find().count()
- Package["msavin:mongol"].Mongol.hideCollection("mongoName");
  
  But you want it to stay there since its important to see how your documents are syncing in between routes.

**Comment by alesch** [comment]
Listen to your customers and please add some quick setting: 'hide velocity collections'. #13

**Comment by msavin** [comment]
Since Velocity is now part of core, it seems reasonable to add a shortcut for it. To hide, update your Mongol and use `Mongol.hideVelocity();` :)
