### ISSUE TITLE
Meteor 1.2.x support? Shell and method orb malfunctions

### ISSUE THREAD

**Issue by PhilVargas** [MeteorToys/allthings#50]
I'm having some issues with the `shell` and `method` orb. 
With the shell orb, trying to type into it causes the background to go white, which causes an illegible white on white text.
The method orb just doesnt display any of my `Meteor.method`s. However, if i switch over to the shell orb i can still execute these methods using `Meteor.call('foo')`

I checked the compatibility page and found toys only supports 1-1.1 . 
are these issues caused because i'm on 1.2.x and if so, can we expect 1.2 to be compatible soon?

ss of meteor shell with focus (cursor is inside shell window)
![screen shot 2015-10-21 at 3 20 52 pm](https://cloud.githubusercontent.com/assets/4534935/10651945/6b431ddc-7807-11e5-9bc3-bb50fb9a49a9.png)

ss of meteor shell without focus (cursor is not inside shell window)
![screen shot 2015-10-21 at 3 20 57 pm](https://cloud.githubusercontent.com/assets/4534935/10651946/6b478a5c-7807-11e5-81a9-1098a7a9cbc9.png)

running on chrome, meteor 1.2.0.2, and allthings 2.1.3

**Comment by msavin** [comment]
Hey Phil, sorry that you are having these issues. I'm curious - what browser are you using with Shell? any CSS frameworks?

Meteor Toys do support 1.2 - and I will be pushing an update soon to solve the Method issue. I'll update you when its ready.

**Comment by PhilVargas** [comment]
using chrome 46 on mac el capitan with foundation 5.
inspecting the shell with focus activated, it looks like foundation 5 is applying a white background to the text area!

**Comment by msavin** [comment]
This issue should be resolved the new 2.2.0 release. To update, remove your Meteor Toys package and run `meteor add meteortoys:allthings@2.2.0`. If this issue repeats, or you have other issues, please let me know. :)
