### ISSUE TITLE
Separate Toys CSS from the App CSS

### ISSUE THREAD

**Issue by lirbank** [MeteorToys/allthings#52]
It would be sweet if all CSS for the UI was separated or hardcoded to make it more resilient to CSS overrides in the app. Ex. see the screenshot below, here I've used global CSS overrides for <button> etc., which screw up Meteor Toys UI making it impossible to provide a value for methods. 

To make Meteor Toys work with this app I have to change the stylesheets so they don't impact on Toys, which is kind of a drag.

![image](https://cloud.githubusercontent.com/assets/2538130/10825737/9bc1abdc-7e23-11e5-8586-16880760e1c5.png)

**Comment by msavin** [comment]
Indeed - there has been a CSS rewrite coming in 2.2 (just a day or two more)

**Comment by msavin** [comment]
I just launched an update that fixed many of these kinks. To update, remove your Meteor Toys package and run `meteor add meteortoys:allthings@2.2.0`. If this issue repeats, or you have other issues, please let me know.

**Comment by lirbank** [comment]
Ok, great! 

I can't yet tell you if this issue has been resolved because of #57

**Comment by msavin** [comment]
Following up to see if issue continues

**Comment by lirbank** [comment]
I'm afraid it's still there. Looks a bit different though:

![image](https://cloud.githubusercontent.com/assets/2538130/11618820/ab32089c-9c54-11e5-8165-7332aee893d1.png)

**Comment by msavin** [comment]
Hmm interesting, and thanks for posting. Are you using any CSS frameworks that I can apply to duplicate the issues, or is it all custom?

**Comment by lirbank** [comment]
It's all custom. Let me know if you want to look at the scss files and I can email them to you.

**Comment by msavin** [comment]
+1 for custom :) would be great if you can send it. I'm working on a new version and would be great to knock this out with it.

**Comment by rklaeboe** [comment]
Still problem when trying to update a  field  (goes white on white).
Why not allow user to override color and background-color with a preference tab?
Second best -- what is now the .css path to set color and background of update window?

**Comment by msavin** [comment]
For that, you can look into ThemeKit. What I suspect is you may be running an old version of MT and/or your CSS framework is overriding them. Can you please send me your version and a screenshot, and if possible package list and/or css?

**Comment by rklaeboe** [comment]
OK -- Uninstalled and reinstalled. Now legible. + will look into ThemeKit when I have some time. 
No longer a problem. Thanks.

**Comment by msavin** [comment]
Great to hear :+1:
