### ISSUE TITLE
Trash not working

### ISSUE THREAD

**Issue by peonmodel** [MeteorToys/allthings#53]
I am having an issue in which things removed from collection through meteortoys is not saved into my trash,
does anyone have the same issue?

also, is there a way to reset the trash collection just like all other collection? i want to empty the bin sometimes

**Comment by msavin** [comment]
Sorry you're having this problem -- it sounds like a new issue. Can you please send a list of your packages, and see if the trash can works when AutoPub is enabled?

**Comment by peonmodel** [comment]
List of packages:
accounts-base@1.2.2
accounts-password@1.1.4
accounts-ui@1.1.6
accounts-ui-unstyled@1.1.8
autoupdate@1.2.4
babel-compiler@5.8.24_1
babel-runtime@0.1.4
base64@1.0.4
binary-heap@1.0.4
blaze@2.1.3
blaze-html-templates@1.0.1
blaze-tools@1.0.4
boilerplate-generator@1.0.4
caching-compiler@1.0.0
caching-html-compiler@1.0.2
callback-hook@1.0.4
check@1.1.0
coffeescript@1.0.11
dburles:mongo-collection-instances@0.3.4
ddp@1.2.2
ddp-client@1.2.1
ddp-common@1.2.2
ddp-rate-limiter@1.0.0
ddp-server@1.2.2
deps@1.0.9
diff-sequence@1.0.1
donaldaverill:serialport@1001.7.4_1
ecmascript@0.1.6
ecmascript-runtime@0.2.6
ejson@1.0.7
email@1.0.8
fastclick@1.0.7
geojson-utils@1.0.4
gwendall:body-events@0.1.6
hot-code-push@1.0.0
html-tools@1.0.5
htmljs@1.0.5
http@1.1.1
id-map@1.0.4
jquery@1.11.4
lai:collection-extensions@0.1.4
launch-screen@1.0.4
less@2.5.1
livedata@1.0.15
localstorage@1.0.5
logging@1.0.8
manuel:isdev@1.0.0
manuel:reactivearray@1.0.5
manuel:viewmodel@1.9.14
mdg:camera@1.2.0
meteor@1.1.10
meteor-base@1.0.1
meteortoys:allthings@2.1.3
meteortoys:authenticate@2.0.0
meteortoys:autopub@2.0.1
meteortoys:blueprint@2.0.2
meteortoys:email@2.0.1
meteortoys:hotreload@2.0.2
meteortoys:listen@2.0.0
meteortoys:method@2.0.0
meteortoys:pro@2.0.0
meteortoys:pub@2.0.0
meteortoys:result@2.0.1
meteortoys:shell@2.0.2
meteortoys:status@2.0.0
meteortoys:sub@2.0.0
meteortoys:throttle@2.0.0
meteortoys:toykit@2.1.2
meteortoys:toypro@2.0.0
minifiers@1.1.7
minimongo@1.0.10
mobile-experience@1.0.1
mobile-status-bar@1.0.6
mongo@1.1.3
mongo-id@1.0.1
msavin:jetsetter@1.4.0
msavin:mongol@1.5.0
npm-bcrypt@0.7.8_2
npm-mongo@1.4.39_1
observe-sequence@1.0.7
ordered-dict@1.0.4
promise@0.5.1
random@1.0.5
rate-limit@1.0.0
reactive-dict@1.1.3
reactive-var@1.0.6
reload@1.1.4
retry@1.0.4
routepolicy@1.0.6
service-configuration@1.0.5
session@1.1.1
sha@1.0.4
spacebars@1.0.7
spacebars-compiler@1.0.7
srp@1.0.4
standard-minifiers@1.0.2
templating@1.1.5
templating-tools@1.0.0
tracker@1.0.9
ui@1.0.8
underscore@1.0.4
url@1.0.5
webapp@1.2.3
webapp-hashing@1.0.5

it doesnt go into trash with or without autopub on, it does shows "Removed did4DKspdk4NtPWb9 from dupe. Back-up below:" Object{}... in the console though

not too sure when it first occured, i suspect the last meteor update

also, unrelated to this problem, is there a way to access the meteor toys authentication details in Meteor.settings so that i dont have to re-authenticate meteortoys each time i create a test repo?

**Comment by msavin** [comment]
This issue should be resolved the new 2.2.0 release. To update, remove your Meteor Toys package and run `meteor add meteortoys:allthings@2.2.0`. If this issue repeats, or you have other issues, please let me know.

Regarding authentication - currently that's the best we can do because its the only way to protect the keys, but I'm looking for other ways.
