### ISSUE TITLE
Error while checking for meteortoys:method@2.2.0

### ISSUE THREAD

**Issue by jurajkrivda** [MeteorToys/allthings#55]
I am getting this error 

meteor add meteortoys:allthings
 => Errors while adding packages:

While checking for meteortoys:method@2.2.0:
error: No compatible binary build found for this package. Contact the
package author and ask them to publish it for your platform.

**Comment by msavin** [comment]
Thanks for reporting - I've noticed too. For some reason, the package system hung up on the update but updated on the server. I've pushed up an update and its corrected now:)
