### ISSUE TITLE
MeteorToys not picking up local collection

### ISSUE THREAD

**Issue by jamielob** [MeteorToys/allthings#56]
If I create a unmanaged (unsynchronized) local collection like so:

```
Local = new Mongo.Collection(null);
```

And populate it with data, I can access it via the console, but it doesn't show up in MeteorToys.

**Comment by msavin** [comment]
Currently - Meteor Toys do not have support for local collections, but that will be changing soon :)

**Comment by jamielob** [comment]
Hi @msavin - Do you have a timeline on supporting local collections?

**Comment by msavin** [comment]
Not yet - but I have the issue for this in the Mongol repo:
https://github.com/msavin/Mongol/issues/123

I'm looking into it and will update on the status. In the meanwhile, I'll close this issue in favor of the one in the Mongol repository.

**Comment by jamielob** [comment]
Hey @msavin - Just FYI, this is such a key feature for me (along with quick searching) that I'm now using constellation instead.

**Comment by msavin** [comment]
Sorry to hear that. I'm hoping to get to it soon.
