### ISSUE TITLE
2.2.0 not compatible with browser-policy package

### ISSUE THREAD

**Issue by lirbank** [MeteorToys/allthings#57]
It seems like 2.2.0 doesn't work if the [browser-policy](https://atmospherejs.com/meteor/browser-policy) package is loaded. I think you can just add a few policy rules to your package and it should take care of it.

In the browser console:
`Refused to load the font 'data:application/font-woff;charset=utf-8;base64,d09GRgABAAAAAGoUABEAAAAAvJA…yA/lwxAAf/NQSDtWIEhivFGIyWigkYLxSHYJIrpuCQK47ANGwpKOEfDz5cKAAAAAABViuSJAAA' because it violates the following Content Security Policy directive: "default-src 'self' [...]". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by lirbank** [comment]
Had some time to look at this, the solution is to configure the browser policies to allow fonts to be loaded from a data: URL, like this:

``` javascript
BrowserPolicy.content.allowFontDataUrl();
```

@msavin since browser-policy is a core package maintained by MDG I think it would make sense for Meteor Toys to support it's use. It's probably as simple as adding a weak dependency to browser-policy and if it's loaded, run the line above. Oh, or just add it to the docs :)

**Comment by msavin** [comment]
Hey there, apologies for the slow response. Regarding adding that code to the package - I am not sure if would be a good idea since it would work across the application in development mode. I'm thinking it would be better to explicitly add to the application - I would guess that is what you had to do in the interim  and it would be great to hear what you think.

**Comment by lirbank** [comment]
Yeah, maybe you're right. I don't really have an opinion, BrowserPolicy users just have to add the line I posted above and it works like a charm, and that solution is totally fine. 

I would just add this finding to the documentation and be done with it. Up 2 you!

**Comment by msavin** [comment]
Thanks - will be good to add to documentation for sure.
