### ISSUE TITLE
Blaze #each issues

### ISSUE THREAD

**Issue by Schonne** [MeteorToys/allthings#6]
I just updated to the latest version and am getting this error in the console and the meteor app breaks:

![image](https://cloud.githubusercontent.com/assets/3167572/7555726/430eb72e-f722-11e4-9298-2fc6b63f174e.png)

removing allthings fixes the problem - reinstalling it breaks it again.

I've tested it on a Mac and Windows machine with the same results.

**Comment by Schonne** [comment]
![image](https://cloud.githubusercontent.com/assets/3167572/7555733/a385bc1a-f722-11e4-829c-e59f25bb06fd.png)

**Comment by msavin** [comment]
Thanks for the report! Can you please check if removing aldeed:template-extension resolves the problem?

**Comment by Schonne** [comment]
I just started using meteortoys again in a project without aldeed:template-extension and it's working fine. I'm not sure if the problem was that package causing a conflict or not, but you can consider this issue closed.
