### ISSUE TITLE
Exception while invoking method 'MeteorToys_x' ReferenceError: Match is not defined

### ISSUE THREAD

**Issue by cvax** [MeteorToys/allthings#60]
When you install this package to Meteor 1.2.1 and run it for the first time via Ctrl+M on the standard default meteor create template it throws this exception.

I20151128-14:27:37.473(-8)?     at [object Object].Meteor.(anonymous function).MeteorToys_x (packages/meteortoys_method/ToyKit/main.js:1:1)
I20151128-14:27:37.472(-8)? Exception while invoking method 'MeteorToys_x' ReferenceError: Match is not defined
I20151128-14:27:37.473(-8)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151128-14:27:37.473(-8)?     at livedata_server.js:708:19
I20151128-14:27:37.474(-8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151128-14:27:37.474(-8)?     at livedata_server.js:706:40
I20151128-14:27:37.474(-8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151128-14:27:37.474(-8)?     at livedata_server.js:704:46
I20151128-14:27:37.475(-8)?     at tryCallTwo (C:\Users\Josh\AppData\Local.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:45:5)
I20151128-14:27:37.475(-8)?     at doResolve (C:\Users\Josh\AppData\Local.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:171:13)
I20151128-14:27:37.475(-8)?     at new Promise (C:\Users\Josh\AppData\Local.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:65:3)

**Comment by limratana** [comment]
I have run into this as well and have emailed the author.

**Comment by rhyslbw** [comment]
+1

**Comment by flexzuu** [comment]
+1

**Comment by cvax** [comment]
Guys, I've figured it out. You will need to add the check package to your projects to use Meteor Toys.
https://atmospherejs.com/meteor/check

meteor add check

**Comment by limratana** [comment]
Should it then not be added automatically when you add Meteor Toys to your project?

**Comment by cvax** [comment]
I've seen this fail on other packages too. Not sure, maybe it was a change with the latest version of Meteor or something that suddenly requires users to manually add the check package.

**Comment by rhyslbw** [comment]
There was a change in 1.2 that requires packages to define explicit dependencies, which is a good thing. Since this is closed source we can't check/patch/PR so leave this open @cvax as it's not resolved

**Comment by msavin** [comment]
Fixed the bug and added check. Please update to meteortoys:allthing@2.3.1 and let me know if that worked. Apologies for the delay.

**Comment by rhyslbw** [comment]
Thanks @msavin fixed for me

**Comment by msavin** [comment]
Thanks for confirmation, closing :)
