### ISSUE TITLE
Tooltips hidden behind collections

### ISSUE THREAD

**Issue by abernix** [MeteorToys/allthings#62]
The z-index of the tooltip cause them to display behind the list of collections when you have a lot of collections.

<img width="171" alt="screen shot 2015-12-02 at 5 06 17 pm" src="https://cloud.githubusercontent.com/assets/841294/11534581/1657822c-9918-11e5-85a8-ba43e992fd91.png">

**Comment by msavin** [comment]
Good catch - fix coming soon

**Comment by msavin** [comment]
This issue has been resolved in Meteor Toys 3, and your new activation code should be in your inbox. Please upgrade and let me know how it works. If you experience any issues, please open a new issue.
