### ISSUE TITLE
Add check as a dependency package

### ISSUE THREAD

**Issue by elie222** [MeteorToys/allthings#63]
I was getting errors that Match wasn't defined in a project. Once I did `meteor add check` the error went away.

**Comment by rhyslbw** [comment]
Dupe https://github.com/MeteorToys/allthings/issues/60

**Comment by msavin** [comment]
Fixed - please update to meteortoys:allthing@2.3.1 and let me know if that worked.

**Comment by msavin** [comment]
I've heard this is working now, so I will close the ticket
