### ISSUE TITLE
Add 'underscore' as a dependency package | using meteortoys within Package.onTest

### ISSUE THREAD

**Issue by peonmodel** [MeteorToys/allthings#65]
While trying to use meteor toys for diagnostic, i encountered:

Uncaught Error: There are multiple templates named 'JetSetter'. Each template needs a unique name. - templating.js:21

and 

Uncaught ReferenceError: _ is not defined - common.js:61

i am trying to use tinytest along with meteortoys to test my local package 'mypackage' like this

```
Package.onTest(function(api) {
  api.use(['ecmascript', 'mongo', 'underscore']);
  api.use('tinytest');
  api.use(['mypackage:package', 'meteortoys:allthings@2.3.1']);
  api.addFiles(['mypackage-tests.js']);
});
```

from my past experience, the _ is not defined error is that 'underscore' is not declared as dependency in the package i am trying to use, meteortoys in this case

**Comment by peonmodel** [comment]
I am rather sure it is the same issue
reference: Add check as a dependency package https://github.com/MeteorToys/allthings/issues/63

**Comment by Anima-t3d** [comment]
Any progress on this?

**Comment by msavin** [comment]
Hey - I am not 100% sure about this issue. Can you please explain again?

**Comment by peonmodel** [comment]
i don't remember the details, it has been some time ago

basically, i created a package, PackageA

then i ran `meteor test-packages PackageA` using the default tinytest

i wanted to have access to meteortoys while testing, so i added 'meteortoys' to the PackageA's Package.onTest `api.use('meteortoys')`

i encountered

```
_ is not defined
```

i had added 'underscore' dependency everywhere, the package i am testing(PackageA) and it's 'onTest' but nothing helps
the problem goes away when i removed meteortoys

some versions of meteortoys ago (sometime before 11 Dec 2015), i could use meteortoys inside another package's onTest api

i encountered similar issue before, in which the package i am dependent on (in this case meteortoys) needs to add 'underscore' as a dependency

Note that this was still using meteor 1.2, i havent tried in meteor 1.3

**Comment by msavin** [comment]
Ah, ok. I'll add it as a dependency on the server, seems like that would fix the problem.

**Comment by msavin** [comment]
This issue has been resolved in Meteor Toys 3, and your new activation code should be in your inbox. Please upgrade and let me know how it works. If you experience any issues, please open a new issue.
