### ISSUE TITLE
meteortoys:toykit Version Downgrade

### ISSUE THREAD

**Issue by abernix** [MeteorToys/allthings#66]
I guess this doesn't affect anything (as everything seems to work), but I have a script that checks all my versions in all my packages and in .meteor/versions against the atmosphere API (for my own reasons, it's done this way.  At some point in November I guess a lower version got published of `meteortoys:toykit` – usually I see package authors do this by mistake.

<img width="269" alt="screen shot 2016-01-11 at 7 20 44 pm" src="https://cloud.githubusercontent.com/assets/841294/12240900/aa264480-b898-11e5-8491-97fb9a89c259.png">

You can also see this on the `meteortoys:toykit` atmosphere page: https://atmospherejs.com/meteortoys/toykit

And as a last point, that page's GitHub link points to some other project: https://github.com/p-j/meteor-gravatar/ (weird)

**Comment by msavin** [comment]
Thanks for letting me know. Working to push a big update that will hopefully resolve this.

**Comment by msavin** [comment]
Ah - I took a second look : yes that was a bug fix in case people were running old versions of Toys, but newer versions should still use the later versions. Thanks for the heads up though :)

**Comment by abernix** [comment]
Cool.  Maybe you still want to update the github link (as I barely mentioned as an afterthought at the bottom of the original issue text). :smile:
