### ISSUE TITLE
Methods orb styling

### ISSUE THREAD

**Issue by ramijarrar** [MeteorToys/allthings#67]
Methods are listed correctly, but after selecting an item from the list it transitions to an empty page:

![image](https://cloud.githubusercontent.com/assets/9661116/12694391/a0603b30-c780-11e5-83e3-f1d322500ccc.png)

![image](https://cloud.githubusercontent.com/assets/9661116/12694402/027884c6-c781-11e5-9f0d-5a07adef3f10.png)

**Comment by ramijarrar** [comment]
Okay, so I took a closer look and the page isn't actually empty:

![image](https://cloud.githubusercontent.com/assets/9661116/12694649/506e1e00-c788-11e5-9f70-4b70e8bfdc64.png)

**Comment by ramijarrar** [comment]
Dug a little deeper and the culprit is the fixed width (306px) applied on `.MeteorToys_Method_contenta, .MeteorToys_Method_contentb`. This is causing the div to overflow likely as a result of some conflict with base styles (e.g reset/normalize). 

Trying with a lower value (up to 288px) or even no value at all resolves this for me. The latter option sounds like the most resilient way to go assuming there are no negative implications.

EDIT: Just noticed #52 and I think this change will probably apply to that issue as well.

**Comment by ramijarrar** [comment]
After using this approach in different projects I have noticed that removing the width altogether will sometimes cause alignment issues whereas the fixed width seems to do the trick consistently.

@msavin would be great if you could integrate this when you get the chance.

**Comment by msavin** [comment]
Thanks for the info - I will fix it up soon. If you can send any CSS code my way, or perhaps, any patching that you are doing on the div selector, it would be great. It sounds like something just needs to be overwritten.

**Comment by ramijarrar** [comment]
I looked through the rules on each of the elements for the Method orb and it doesn't look like my app styles are overwriting anything. I'd assume this has something to do with conflicting/missing base styles which would be harder to detect. In all cases, adding a fixed width of 288px on `.MeteorToys_Method_contenta, .MeteorToys_Method_contentb` does the trick without breaking anything for other projects that never had this issue.

**Comment by ramijarrar** [comment]
BTW - For the next version of Meteor Toys, I definitely second the idea of moving to a browser add-on or something similar (as proposed [here](https://forums.meteor.com/t/feedback-request-for-the-upcoming-meteor-toys-3/17202/3)) if it feasible. I think it would be a big plus for UX and would eliminate most issues related to decoupling.

**Comment by ramijarrar** [comment]
(Ignore that - mixed up between tabs while trying to close a different issue)

**Comment by ramijarrar** [comment]
@msavin Any updates on this?

**Comment by ramijarrar** [comment]
@msavin Is there anything blocking this? Seems like a really straightforward fix.

**Comment by ramijarrar** [comment]
Bump.

**Comment by msavin** [comment]
Hey - I fixed some of the issues in regards to this but have not been able to replicate this one. Consider 288px works for you but 306 doesnt (the 18px difference is how much padding the div has), it sounds like you are using a browser that does not support box-sizing or perhaps a framework that heavily overrides it. Could you please let me know your browser, os and package list?

**Comment by msavin** [comment]
This issue has been resolved in Meteor Toys 3, and your new activation code should be in your inbox. Please upgrade and let me know how it works. If you experience any issues, please open a new issue.

**Comment by ramijarrar** [comment]
No more styling issues with v3 :)

**Comment by msavin** [comment]
Woohoo!
