### ISSUE TITLE
Chrome Warning

### ISSUE THREAD

**Issue by humbertocruz** [MeteorToys/allthings#69]
Google Chrome is displaying this warning: 'Object.observe' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/6147094632988672 for more details.

**Comment by msavin** [comment]
It's sad that they are deprecating it - it was a super cool feature. For now, it works, but in the next update I'll remove it.

**Comment by jlukic** [comment]
Would love to see

**Comment by drabanus** [comment]
I observe that with this error message, the "Mongol" variable viewer, invoked with Ctrl-M, does not display any document entries from collections. Has that something to do with the deprecated "Object.observe" function?

**Comment by msavin** [comment]
Sorry that its taking so long - hands are full. However, Meteor Toys try to use Object.observe first, and if its not available, they fall back to polling every second or so. It should work for as long as Chrome returns undefined for Object.observe. If Chrome is not already making Object.observe undefined, I can suggest hacking it at least for now.

``` javascript
if (Package["msavin:mongol"]) {
    Object.observe = undefined;
}
```

**Comment by msavin** [comment]
This issue has been resolved in Meteor Toys 3, and your new activation code should be in your inbox. Please upgrade and let me know how it works. If you experience any issues, please open a new issue.

**Comment by jlukic** [comment]
Thanks Max Savin for saving maximum errors #badpuns
