### ISSUE TITLE
Cannot read property 'email' of undefined

### ISSUE THREAD

**Issue by Miz85** [MeteorToys/allthings#7]
Hi !

First of all  just want to say meteortoys are amazing !

They're working fine with my meteor app but they keep throwing this error on the server side: 

```
=> App running at: http://localhost:3000/
I20150517-12:30:30.218(2)? Exception while invoking method 'MeteorToys' TypeError: Cannot read property 'email' of undefined
I20150517-12:30:30.219(2)?     at [object Object].Meteor.(anonymous function).MeteorToys (packages/meteortoys:shell/server/main.js:1:1)
I20150517-12:30:30.220(2)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150517-12:30:30.220(2)?     at packages/ddp/livedata_server.js:648:1
I20150517-12:30:30.220(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150517-12:30:30.220(2)?     at packages/ddp/livedata_server.js:647:1
I20150517-12:30:30.220(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150517-12:30:30.220(2)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150517-12:30:30.220(2)?     at packages/ddp/livedata_server.js:546:1
```

Would you have an idea of where that comes from ?

Thanks :)

**Comment by Gaelan** [comment]
:+1:

**Comment by miri-am** [comment]
+1 
in my case the reason is probably that I am not using the email-field for my Meteor.users collection.

**Comment by MrPilotSir** [comment]
I am wondering this also, even on a very basic start to my project where the only thing I have that is related to email is the accounts-password and accounts-ui

Any help would be appreciated :-)

**Comment by msavin** [comment]
I am pretty sure this is fixed in 1.1.0, can you please update and let me know how its working?

**Comment by msavin** [comment]
Also thought its good to mention that even though Meteor logs this error - it is not harmful. It's just saying it can't find a value for a variable.

**Comment by Miz85** [comment]
Hi !

I just upgraded the meteortoys:allthings package to 1.1.0 and it seems that the error message is gone.

Thanks a lot !
