### ISSUE TITLE
Methods list is incomplete (limited # of methods listed?)

### ISSUE THREAD

**Issue by jowilhnson** [MeteorToys/allthings#70]
My list of methods isn't complete, it lists all methods that start with an uppercase letter, followed by all lowercase methods, but the lowercase only go up to those that start with 's' and anything later in the alphabet isn't listed. 

I can change the name of a method that starts with 'u' to start with 'U' and it will appear in the beginning of the list with the other uppercase. 

I can't make sense of if there's a hard limit or not however. If I change a 'greater than' 's' method to an uppercase it appears with the uppercase names and adds to the total list count (61). If I change an 's' or lower to uppercase, it moves to the uppercase portion of the list, the total number of items doesn't change, and no further lowercase items are shown. But, if I change an 's' or lower method and add a lowercase 'z' to the beginning of the name, it will no longer appear in the list as it is past the alphabetical cutoff, BUT, there will now be one further method listed at the end of the list. 

So, I can push the list total past 60, can get the lowercase section below 48 by changing listed method names to uppercase, can keep it at 48 and get new methods shown by changing a lowercase to an unlisted lowercase (z,y,x,etc), but can never have more than 48 total lowercase named methods.

**Comment by msavin** [comment]
Hmmm - interesting problem. How are you writing your methods? Are they just as per the documentation or? 

There is no hard limit to how many methods the application could have either.

**Comment by jowilhnson** [comment]
Well, looks like there's been some changes to the documentation, and probably the methods api since I first learned the syntax. I've been using the basic format:
`methodName: function(args){}`

But it looks like there are other, and more advanced ways to write them. If I get some time I'll try writing some in other formats and see if that effects the list of methods.

**Comment by msavin** [comment]
Well, if it's the basic version then it shouldn't have much issues. How are you writing them? I.e.  Isomorphic or in packages or? Hmm 🤔

**Comment by jowilhnson** [comment]
All my methods are in a single file, in a single Meteor.methods({}) block. Think that might be part of my problem? I started building this project as I was learning meteor, mostly from tutorials based around 0.9 or 1.0, so it's monolithic and not especially elegant in design.

**Comment by msavin** [comment]
Meteor Toys 3 just shipped, which have many fixes. I've had trouble replicating this, but see if it works better with Meteor Toys 3. If not, please open a new issue.
