### ISSUE TITLE
1.3 support? Mantra? ReactiveDict

### ISSUE THREAD

**Issue by fallenpeace** [MeteorToys/allthings#71]
Features seem to be broken sadly in a 1.3 Meteor/Mantra setup.

Sessions and reactiveDict, are not working at all.

**Comment by msavin** [comment]
Hmm - you know, Mantra is virtually a different stack than Meteor. I have not looked into if/how Meteor Toys could work with it.

**Comment by fallenpeace** [comment]
@msavin, what do you mean by "different stack"? I figured Mantra is simply and architecture on top of meteor. Sort of how the MDG has "Meteor Guide". The mentioned features arent working for me either on a fresh 1.3 regular.

**Comment by msavin** [comment]
Hmm, interesting. What does your 1.3 setup look like? Could you send a list of packages?

**Comment by jesseflorig** [comment]
So is vanilla Meteor 1.3 supported? It seems to be broken on my fresh project init.

**Comment by msavin** [comment]
Some features are broken, but a fix is coming

**Comment by jesseflorig** [comment]
@msavin Awesome, thanks for the response. FYI I was having issues with mongol, but once I imported my collection on the client it was fine (womp womp).

**Comment by msavin** [comment]
Meteor Toys 3 should work better with Meteor 1.3, and your new activation code should be in your inbox. Please upgrade and let me know how it works. Note that if you are using collections via modules, you must import it to the global namespace. You can wrap the import in the core Meteor Toys package or a debugOnly package to prevent it fro going into production. If you experience any issues with Meteor Toys 3, please open a new issue.
