### ISSUE TITLE
Problems when using separate Database in development

### ISSUE THREAD

**Issue by hanskohls** [MeteorToys/allthings#73]
I just moved my development environment to a separate local mongo database, so that I can configure external access to it and control the version of mongodb. For various reasons I wanted to run this without authentication. 

This seems to trigger an issue with the meteor toys. Stack trace is below: 

I20160402-23:09:38.621(1)? Exception while invoking method 'MeteorToys_ia' TypeError: Cannot read property 'username' of null  
I20160402-23:09:38.622(1)?     at [object Object].Meteor.(anonymous function).MeteorToys_ia (packages/meteortoys_authenticate/server/methods.js:1:1)  
I20160402-23:09:38.622(1)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)  
I20160402-23:09:38.622(1)?     at livedata_server.js:708:19  
I20160402-23:09:38.622(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)  
I20160402-23:09:38.623(1)?     at livedata_server.js:706:40  
I20160402-23:09:38.623(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)  
I20160402-23:09:38.623(1)?     at livedata_server.js:704:46  
I20160402-23:09:38.623(1)?     at tryCallTwo (/home/hans/.meteor/packages/promise/.0.5.1.1550ocw++os+web.browser+web.cordova/npm/node_modules/meteor-prom
ise/node_modules/promise/lib/core.js:45:5)  
I20160402-23:09:38.623(1)?     at doResolve (/home/hans/.meteor/packages/promise/.0.5.1.1550ocw++os+web.browser+web.cordova/npm/node_modules/meteor-promi
se/node_modules/promise/lib/core.js:171:13)  
I20160402-23:09:38.624(1)?     at new Promise (/home/hans/.meteor/packages/promise/.0.5.1.1550ocw++os+web.browser+web.cordova/npm/node_modules/meteor-pro
mise/node_modules/promise/lib/core.js:65:3)  
I20160402-23:09:40.065(1)? Exception while invoking method 'MeteorToys_ia' TypeError: Cannot read property 'username' of null  
I20160402-23:09:40.065(1)?     at [object Object].Meteor.(anonymous function).MeteorToys_ia (packages/meteortoys_authenticate/server/methods.js:1:1)  
I20160402-23:09:40.065(1)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)  
I20160402-23:09:40.066(1)?     at livedata_server.js:708:19  
I20160402-23:09:40.066(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)  
I20160402-23:09:40.066(1)?     at livedata_server.js:706:40  
I20160402-23:09:40.066(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)  
I20160402-23:09:40.066(1)?     at livedata_server.js:704:46  
I20160402-23:09:40.067(1)?     at tryCallTwo (/home/hans/.meteor/packages/promise/.0.5.1.1550ocw++os+web.browser+web.cordova/npm/node_modules/meteor-prom
ise/node_modules/promise/lib/core.js:45:5)  
I20160402-23:09:40.067(1)?     at doResolve (/home/hans/.meteor/packages/promise/.0.5.1.1550ocw++os+web.browser+web.cordova/npm/node_modules/meteor-promi
se/node_modules/promise/lib/core.js:171:13)  
I20160402-23:09:40.067(1)?     at new Promise (/home/hans/.meteor/packages/promise/.0.5.1.1550ocw++os+web.browser+web.cordova/npm/node_modules/meteor-pro
mise/node_modules/promise/lib/core.js:65:3)

**Comment by msavin** [comment]
Ah I see - I guess I did not account for situations where accounts-base would not be present. I will fix it up in the coming release.

**Comment by msavin** [comment]
This issue has been resolved in Meteor Toys 3, and your new activation code should be in your inbox. Please upgrade and let me know how it works. If you experience any issues, please open a new issue.
