### ISSUE TITLE
Refused to load the font on Version 50.0.2661.86 (64-bit) (Linux)

### ISSUE THREAD

**Issue by ahhmarr** [MeteorToys/allthings#74]
Refused to load the font 'data:application/font-woff2;charset=utf-8;base64,d09GMgABAAAAAFQ0ABEAAAAAvI…rnptIwTkWGE9bL/2LchXN+inLcDLxE7fAT7xFB4hM6CbaEib4mSsIr4jjCV4pIX7nsL37WAw==' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

I'm using it with https://github.com/themeteorchef/base

**Comment by msavin** [comment]
Thanks for the heads up. It's a conflict with browser policy settings. If you can let it load embedded fonts, that would fix it, but new version will resolve that shortly.

**Comment by msavin** [comment]
This issue has been resolved in Meteor Toys 3, and your new activation code should be in your inbox. Please upgrade and let me know how it works. If you experience any issues, please open a new issue.
