### ISSUE TITLE
Meteor Toys 3, Method list won't show method names that begin with 'update'

### ISSUE THREAD

**Issue by jowilhnson** [MeteorToys/allthings#75]
Continuing issue #70, still occurring in Meteor Toys 3. 

Was finally able to narrow this down to a specific trigger. Refactored all methods to camelCase naming. Had 61 methods displaying in list, ending with 'studentUpdate'. Thought nothing past 's' names were showing. Through refactoring, removed a few methods, list then displayed 58 methods, ending with 'studentRemove'. 

Occurred to me that I probably didn't have that many methods alphabetically beyond that. Browsed through, realized I didn't have any 't' methods. Renamed 'updateTestLanguage' method to 'testLanguageUpdate', and it appeared in the method list. Renamed 'updateUserLayout' to 'userLayoutUpdate' to test if there was an issue with 'u' names. 'userLayoutUpdate' appears in the method list. 

So, my conclusion is that only methods beginning with the word 'update' do not show up in the method list. Methods beginning with 'Update' do appear, grouped with any other capitalized method names at the top of the list. 

Odd issue, to say the least. I probably would never have noticed it except I had a method starting with 'update' that I was needing to run manually quite often during a spell of debugging. Easy enough to work around with simple renaming.

**Comment by msavin** [comment]
This should be fixed with the latest update. Please remove and add the package and let me know how it works.

**Comment by msavin** [comment]
And thanks for the report, it was helpful in catching the bug 😎

**Comment by jowilhnson** [comment]
Works now, all methods are showing up in the list. Thanks for the update, and thanks for making such a great tool, can't imagine doing meteor development without it.
