### ISSUE TITLE
1email gets spammed into console with meteor toys 3

### ISSUE THREAD

**Issue by kulttuuri** [MeteorToys/allthings#76]
Hi,

We just updated 2 different users to meteor toys 3. After activating, meteor's console gets spammed with message "1emailaddress" couple times when the application starts and every time page gets refreshed (message gets spammed 2-4 times every refresh). Have tried restarting meteor with no success.

**Comment by kulttuuri** [comment]
1emailaddress means that emailaddress is the email-address for which meteor toys is registered for. I just didn't write it here for security reasons.

**Comment by ramijarrar** [comment]
We are seeing the same behavior

**Comment by msavin** [comment]
This should be fixed with the latest update. Please remove and add the package and let me know how it works.

**Comment by Anima-t3d** [comment]
Confirmed to be fixed.
