### ISSUE TITLE
Importing collections via modules not showing in Meteor Toys

### ISSUE THREAD

**Issue by Anima-t3d** [MeteorToys/allthings#79]
> Note that if you are using collections via modules, you must import it to the global namespace. You can wrap the import in the core Meteor Toys package or a debugOnly package to prevent it from going into production.

I don't seem to get my imported collection to show up in Meteor Toys 3 using the method described above.

In lib.js:

```
// in app defined, works in Meteor Toys
Dummy = new Mongo.Collection('Dumb');
// TestCollection is imported and detected in meteor shell, but not in Meteor Toys
ImportedTestCollection = TestCollection;
```

Questions:
- Does it matter where and how the imported collection is defined?
- Does it need to be defined using `new Mongo.Collection()`?

**Comment by Anima-t3d** [comment]
Based on CHANGES.md I tried:

> To add a collection to the list, use: “Package[“msavin:mongol”].Mongol.showCollection(‘collectionName’)’

A collection with given name shows up in Meteor Toys, but it doesn't show any content. I can add collections with any name (even non-existing collections), when I try to add something to the collection by using Meteor Toys it gives an error: **Strange, there was an error inserting your document.**

Please advise, thanks.

**Comment by msavin** [comment]
Hmm, strange indeed! Can you please send a list of packages and let me know
how you set up your collections?

Additionally, what often does the trick is moving Mongol to the top of your
package list.

**Comment by Anima-t3d** [comment]
My code is something as follows:
In a package/module test.js:

``` javascript
import {Mongo} from 'meteor/mongo';
TestCollection = new Mongo.Collection('T_collection');
export { TestCollection };
```

In a package/module mainModule.js:

``` javascript
import { TestCollection } from './collections/UserVersions/test.js';
export { TestCollection };
```

In the app:

``` javascript
import { TestCollection } from 'meteor/test:package';
XTestCollection = TestCollection;
```

It is not showing in Meteor Toys, I can query it in console.
If I try `Package["msavin:mongol"].Mongol.showCollection('T_collection')` in the browser console, it does show an empty collection in Meteor Toys. But when I try to insert something I get the following error in the server console: `Exception while invoking method 'Mongol_insert' ReferenceError: T_collection is not defined`

**Note:** I am using the latest version of Meteor (1.3.2.4).
Moving Mongol to the top of the package list does not seem to have any effect. Other packages are unlikely to be the culprit since I can access the collections in the browser console.

Thanks.

**Comment by msavin** [comment]
Hmm - since its returning a method error, perhaps you also need to export the collection on your server?

**Comment by Anima-t3d** [comment]
I did export it to both client and server and I can access the collections outside Meteor Toys. _It seems to me an issue with Meteor Toys itself?_ 
**Can you make a collection in a module and export it and then verify whether you can see it in Meteor Toys.** 
If you can, please show me the example so I can update my code. Otherwise we will need to debug it further.

Thanks!

**Comment by Anima-t3d** [comment]
Nobody else having this problem?

**Comment by peonmodel** [comment]
@msavin hej i am also having issues with my collections not being seen my meteortoys, not too sure what did i do wrong, here is a repo: https://github.com/peonmodel/bookish-pancake

in the repo, i have package A with collectionA and package B with collection B
in the app itself, i have collectionC, and i imported both collectionA and B

clicking on the button, i print out all 3 collections, and i can make modifications to all 3

meteortoys doesnt not seems to detect collectionA or B despite setting them as global variable, i can access CollectionA and CollectionB in browser console

meteortoys does not detect CollectionC initially though it detected on the 2nd rebuild of the server, i can also force the detection by "Package["msavin:mongol"].Mongol.showCollection('C_collection')" 

how do i let meteortoys detect collections imported from packages?

**Comment by msavin** [comment]
hmm still trying to wrap my head around it. have you tried to place
meteortoys:allthings to the top of the package file? or perhaps right after
meteor-base

**Comment by crs48** [comment]
I'm experiencing the same problem. I'm using https://github.com/thereactivestack/meteor-webpack, so my collections are not created until after Meteor.startup. Is there a way to manually run the Mongol command that calls `Mongo.Collection.getAll()` after all of my collections have been created?

**Comment by peonmodel** [comment]
> hmm still trying to wrap my head around it. have you tried to place
> meteortoys:allthings to the top of the package file? or perhaps right after
> meteor-base

ok, that solves it, i need to include meteortoys as a package BEFORE the packages that export the collection, in my repo, the issue resolve itself after the swap the order of how the packages are used

```
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var            # Reactive variable for tracker
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifier-css   # CSS minifier run for production mode
standard-minifier-js    # JS minifier run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

autopublish             # Publish all data to the clients (for prototyping)
insecure                # Allow all DB writes from clients (for prototyping)

meteortoys:allthings  # <<< this works
toys:package-a
toys:package-b
```

```
toys:package-a
toys:package-b
meteortoys:allthings  # <<< this doesnt
```

turns out the order the packages are added is the problem

a minor quibble, Package["msavin:mongol"].Mongol.showCollection function will blindly accept and string and add to the display even when the collection is non-existence, it will show up in the Mongo Pro menu and gives error for everything done to it

**Comment by Anima-t3d** [comment]
No, it is still not solved. I tried to check out @peonmodel code, but it is already removed. I think it has to with scope of packages? As in Meteor Toys need more than meets the eye... being a module/package that no longer has global vars leaking into the main app, might disable Meteor Toys from picking it up inside the package?

**Comment by msavin** [comment]
Hmm - I think in your last sentence you explained the issue. Mongol/Meteor Toys usually target the global variables to work their stuff, so that required you to export the variables into the global namespace. The code for that can be implemented in the blank main.js file in the allthings so that it doesn't ship to production. But from what I understand that didn't work for ya.. so I gotta think some more on it.

**Comment by Anima-t3d** [comment]
It seems like it does show up in the app once I add some insert/modification on server startup. Even though the app can access the collection, MeteorToys only picks up on it once the app actually does something with it (on startup)?

**Comment by Anima-t3d** [comment]
In the not working situation I have observed that when adding to the collection through a method called from the client it briefly updates the collection, but then it disappears again (after simulation is done).

**Comment by Anima-t3d** [comment]
@msavin Does meteor toys rely on client-side publication? 
If `autopublish` package is enabled or I make the client-side `mainModule` import the `publications.js` (even though the content of that file is wrapped in a `Meteor.isServer` if block) it shows up in Meteor Toys, the moment I do not import the `publications.js` it no longer shows up.

**Comment by Anima-t3d** [comment]
Importing the publication in a server mainModule seems to work.
In the package.js file of the module/package containing the collection:

``` javascript
Package.onUse(function(api) {
    api.versionsFrom('1.3.2.4');
    api.use([
        'ecmascript'
    ]);
    api.mainModule('test.js', 'server');
    api.mainModule('test-client.js', 'client');
});
```

In the test.js file:

``` javascript
import './collections/test/server/publications.js';
```

**Comment by msavin** [comment]
Whoa - did not see coming! 

Thanks for solving this - I will keep it open if anyone runs into the same issue and looking to resolve it in the next release.

**Comment by Anima-t3d** [comment]
It would be good if other people could reproduce the issue and get it solved by applying the solution. This way we can be sure that it actually solves the issue.

In any case, happy to help.
