### ISSUE TITLE
How can I control rate of throttle?

### ISSUE THREAD

**Issue by SharadKumar** [MeteorToys/allthings#81]
After activating throttle, I can see data over the wire is slower and it helped bash some bugs, but we need a bit slower to see some more it seems! Possible?

Thanks.

**Comment by msavin** [comment]
Sorry for the slow response here! The new Throttle is more flexible with the speed. It now lets you toggle two options. The latter sort of "pushes the limit" of how much you can throttle a Meteor app. I'll be sending more information in the customer update in a bit.
