### ISSUE TITLE
Polling exception on "MeteorToys:Impersonate" when using remote DB with oplogs

### ISSUE THREAD

**Issue by brucejo75** [MeteorToys/allthings#83]
I have set up a single instance mongo DB replica set to run on a remote machine using the [oplog observe driver](https://github.com/meteor/docs/blob/version-NEXT/long-form/oplog-observe-driver.md).

I am getting the following exception on meteor toys.  The first exception is this:

```
Exception while polling query {"collectionName":"MeteorToys.Impersonate","selector":{},"options":
{"transform":null,"limit":15}}: MongoError: connection to [192.168.1.111:27017] timed out
```

After the first one, all of the exceptions become this:

```
Exception while polling query {"collectionName":"MeteorToys.Impersonate","selector":{},"options":
{"transform":null,"limit":15}}: Error: No replica set member available for query with
ReadPreference undefined and tags undefined
```

Here are my relevant MONGO environment variables:

```
MONGO_OPLOG_URL=mongodb://XXX:XXX@192.168.1.111:27017/local?authSource=admin
MONGO_URL=mongodb://192.168.1.111:27017/db?replicaSet=rs0&connectTimeoutMS=60000&socketTimeoutMS=60000
```

Any clues?  Or advice on any settings I should change?
Thanks!

**Comment by ramsaymax** [comment]
I just ran into this issue and it turned out to be an issue with my index. I didn't have the field I was querying for indexed properly.

**Comment by brucejo75** [comment]
Thanks @markhallaby, I no longer see this error.  Maybe I corrected this to.  Closing
