### ISSUE TITLE
Upgrading Indirect Dependencies

### ISSUE THREAD

**Issue by adrianmcli** [MeteorToys/allthings#85]
I recently upgraded to the latest version of Meteor for one of my projects and of course, it also updated Meteor Toys.

However, for some reason, there are a whole bunch of Meteor Toys packages that are considered indirect dependencies. What should I do about this?

```
Newer versions of the following indirect dependencies are
available:
 * dburles:mongo-collection-instances 0.3.4 (0.3.5 is
available)
 * lai:collection-extensions 0.1.4 (0.2.1_1 is available)
 * meteortoys:authenticate 2.1.0 (3.0.0 is available)
 * meteortoys:autopub 2.1.0 (3.0.0 is available)
 * meteortoys:blueprint 2.1.0 (3.0.0 is available)
 * meteortoys:email 2.1.0 (3.0.0 is available)
 * meteortoys:hotreload 2.1.0 (3.0.0 is available)
 * meteortoys:listen 2.1.0 (3.0.0 is available)
 * meteortoys:result 2.1.0 (3.0.0 is available)
 * meteortoys:shell 2.1.0 (3.0.0 is available)
 * meteortoys:status 2.1.0 (3.0.0 is available)
 * meteortoys:sub 2.1.0 (3.0.0 is available)
 * meteortoys:throttle 2.1.0 (3.0.0 is available)
 * meteortoys:toykit 2.2.1 (3.0.4 is available)
 * msavin:jetsetter 1.5.2 (2.0.0 is available)
 * msavin:mongol 1.6.2 (2.0.1 is available)
```

**Comment by msavin** [comment]
It looks normal to me - the allthings package just wraps all of those into
one to keep your package list clean. It does look like you are stuck on an
old version of Toys though!

**Comment by adrianmcli** [comment]
@msavin So I should uninstall and re-install Meteor Toys then? I'm just afraid that I'll have these stale packages lying around in my app.

**Comment by msavin** [comment]
Nah no way man, Meteor will remove them too. You can run meteor list to
double check. I believe a meteor reset will reset the local cache too.

**Comment by adrianmcli** [comment]
Excellent! Thx for the help, keep up the great work :)
