### ISSUE TITLE
ejson.js:500 Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by master7xx** [MeteorToys/allthings#86]
![image](https://cloud.githubusercontent.com/assets/7098987/17506285/489a0f1c-5e10-11e6-92ce-2eb028d2d698.png)
When inspecting template.
Tempate contains subtemplate and alethes-pages pagination.

**Comment by msavin** [comment]
I'm not sure if fixable as Blueprint is designed to support the "stock" Blaze. Can you send list of packages?

**Comment by master7xx** [comment]
blaze-html-templates     1.0.5 
check                    1.2.4  
ecmascript               0.6.0  
ejson                    1.0.13  
electronifiejs:pages     1.8.9  
es5-shim                 4.6.15  
fourseven:scss           3.8.0_1*
insecure                 1.0.7  
iron:router              1.0.13  
jabbslad:basic-auth      0.2.2  
jparker:crypto-core      0.1.0  
jparker:crypto-md5       0.1.1  
jquery                   1.11.10
materialize:materialize  0.97.0\* 
meteor-base              1.0.4  
meteortoys:allthings     3.0.0  
momentjs:moment          2.16.0  
mongo                    1.1.14  
peerlibrary:xml2js       0.4.8_1
percolate:synced-cron    1.3.2  
reactive-var             1.0.11  
session                  1.1.7  
shell-server             0.2.1  
standard-minifier-css    1.3.2  
standard-minifier-js     1.2.1  
tracker                  1.1.1  
underscore               1.0.10

**Comment by msavin** [comment]
I think most is likely a package compatibility issue. I am pushing up a new update soon - update coming. Please try it out and let me know if this issue continues.
