### ISSUE TITLE
There was an error updating/duplicating/removing your document.

### ISSUE THREAD

**Issue by Yonben** [MeteorToys/allthings#88]
Hi,

I'm working on an app, and I don't understand why but I keep getting "There was an error" on any operation.. What could be the cause and how can I investigate it (no messages in console..).

It runs on Meteor 1.4 with React (and TrackerReact to handle the sub).

Thanks !

**Comment by msavin** [comment]
Does removing Meteor Toys solve the problem?

**Comment by msavin** [comment]
This is now working with the new Mongol 4.0. Just update the package and you should be good to go :)

Meteor Toys has also been patched up to work in these situations, I will be sending the new keys out shortly.

If you run into any issues, please let me know.
