### ISSUE TITLE
[bug] A lot of data breaks AutoPub toggle

### ISSUE THREAD

**Issue by sylido** [MeteorToys/allthings#89]
We have lots of collections full with lots of records, the autopub was left to "ON" by someone and any attempts to toggle the switch after we `ctrl + m` was met with non-activity. The loading of all our collections would probably take minutes, the autopub button should somehow get priority in cases like these - i.e. if the autopub button is clicked, stop all publications/subscriptions and respect the new value.

**Comment by msavin** [comment]
Yes - this is hard because autopublish in general is not mean't to be used with huge databases. The entire browser window gets slowed down. However, I'll bake in something for the server to disable AutoPub via meteor shell.

**Comment by msavin** [comment]
Meteor Toys 4 now have `Package['meteortoys:autopub'].disable()`, which lets you turn off the functionality. Email update coming on this subject soon.

Keep in mind, whether its AutoPub or the native autopublish, its intended to be used for productivity. If you try to publish a huge database, you will naturally run into memory and performance problems.
