### ISSUE TITLE
Add tooltips to the buttons

### ISSUE THREAD

**Issue by TimBroddin** [MeteorToys/allthings#9]
I'm sometimes confused by the different buttons. It would be nice to add tooltips to them.

Thanks!

**Comment by alesch** [comment]
+1

**Comment by praneybehl** [comment]
+1

**Comment by ramijarrar** [comment]
+1

**Comment by msavin** [comment]
Coming soon :smile:

**Comment by dandv** [comment]
:+1:

**Comment by msavin** [comment]
Boom, we have it now :) 

To upgrade, remove Meteor Toys then run `meteor add meteortoys:allthings@2.0.0`
