### ISSUE TITLE
Won't see any passable parameters in meteor toys Method panel

### ISSUE THREAD

**Issue by kulttuuri** [MeteorToys/allthings#90]
I've never really realized how the method calling in meteor toys works. Maybe I am missing something but using the meteor toys methods functionality I can only call the methods without passing any parameters, none of the parameters that can be passed to the method are there to be added to the call.

I have all my server meteor methods exposed like this:
Meteor.methods({
  'addGame': function(name, instruction) {
    ... functionality ...
  }});

And when bringing up the meteor toys by pressing Ctrl + M, opening the "Method" panel and finding my method "addGame" it doesn't allow me to pass me in any of those parameters: name or functionality. Those parameters are not visible there in the panel, I can only see the "call" button. Is there some extra comments I need to add the method or construct those server methods differently to make the parameters visible to meteor toys?

And this is the package I have currently installed: meteortoys:allthings 3.0.0  Insanely Handy Development Tools. I am using the paid version of meteor toys. I am using latest version of Meteor (1.4), but I've never seen any method parameters to be able to be passed in meteor version 1.2 or 1.3.

**Comment by msavin** [comment]
Ah - yes this is a bug that will be fixed soon. I've been using Todos app as the base for building MT, and they patch the div element:

``` css
div {
    box-sizing: border-box'
}
```

This will be fixed soon, but that snippet should help in the interim.

**Comment by kulttuuri** [comment]
Fantastic! And thanks for the great product – We've been using this on daily basis now. :) +1

**Comment by kulttuuri** [comment]
Any progress on this one? :) btw just noticed your supermongol package, will definitely purchase that one too.

**Comment by msavin** [comment]
Thanks man :) and yes coming soon, aiming for Monday

**Comment by msavin** [comment]
Meteor Toys has also been patched up to work in these situations so I will close this issue. Customer update coming in a bit.
