### ISSUE TITLE
Invalid Credentials: Please try again.

### ISSUE THREAD

**Issue by pedronieto84** [MeteorToys/allthings#91]
Hello, I am developing on local, and I bought Meteortoys, I got the credentials on 12th of November. And I followed all the steps:
1.- add meteortoys:allthings
2.- remove mongol and jetsetter (although this was not necessary since I didn't have them installed)
3.- put the credentials and the email

But I receive a "Invalid Credentials: Please try again".

I am using Meteor 1.1.0.2.
My user is "pedro.nieto.sanchez@gmail.com" I bought the software through gumroad 7th of november.

How can I fix it?

**Comment by msavin** [comment]
Meteor Toys has also been patched to work better here, I will be sending out a customer update briefly.
