### ISSUE TITLE
Meteor Toys in production

### ISSUE THREAD

**Issue by PolGuixe** [MeteorToys/allthings#93]
Somehow I can access Meteor Toys in production. Is this normal? 

I thought that Meteor Toys was a debug only package.

**Comment by PolGuixe** [comment]
Solved. My fault.

**Comment by rpesciotta** [comment]
@PolGuixe I have the same issue. How did you solve it? I do meteor build, deploy it manually and when I run, toys are there.. only started recently, not sure what changed, but I cannot remove it from PROD build.
