### ISSUE TITLE
Meteor toys not showing custom parameters for users

### ISSUE THREAD

**Issue by oskarOlausson** [MeteorToys/allthings#97]
I added a parameter admin to my user profile like so:

`Accounts.onCreateUser(function(options, user) {
   // Use provided profile in options, or create an empty object
   user.profile = options.profile || {};
   // Add admin status
   user.admin= options.admin; //this does not show up in meteor toys
   // Returns the user object
   return user;
});`

Which shows up in my database, (..."username" : "oskar", "profile" : {  }, "admin" : true }) but it does not show up in meteor-toys

`{
  "_id": "JJi2Z8g8buAZdC2Q8",
  "profile": {},
  "username": "oskar"
}`

This is really confusing since I like to use meteor toys to make sure the right information got passed.

**Comment by msavin** [comment]
Which toy in specific? Mongol or Impersonate?

If Mongol - are you publishing the fields to client?

**Comment by msavin** [comment]
It sounds like you are not publishing that data to the client. Toggling AutoPub will probably get it to show.

In either case, as I have not heard from you in a while, I will close this issue. If it persists, please open a new ticket with some more information.
